import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { Pool, type PoolClient } from "pg";
import { maintenanceConfig } from "./config.js";
import { decryptBackup, safeChild, sha256File, validateExtractedBackup, writeEncryptedBundle } from "./bundle.js";

type Job={id:string;owner_id:string;kind:"backup_create"|"backup_verify"|"restore_plan"|"restore_apply";input:Record<string,unknown>;attempts:number;max_attempts:number};
const pool=new Pool({connectionString:maintenanceConfig.DATABASE_URL,max:2});
const encryptionKey=Buffer.from(maintenanceConfig.BACKUP_ENCRYPTION_KEY_HEX,"hex");
const workspaceRoot=path.resolve(maintenanceConfig.OMEGA_WORKSPACE_ROOT);
const backupScript=path.join(workspaceRoot,"infra","backup","backup.ps1");

function run(binary:string,args:string[],cwd=workspaceRoot){return new Promise<string>((resolve,reject)=>{const child=spawn(binary,args,{cwd,windowsHide:true,stdio:["ignore","pipe","pipe"]});let stdout="",stderr="";child.stdout.setEncoding("utf8").on("data",value=>stdout+=value);child.stderr.setEncoding("utf8").on("data",value=>{if(stderr.length<16_384)stderr+=value;});child.on("error",reject);child.on("exit",code=>code===0?resolve(stdout.trim()):reject(new Error(`maintenance_command_failed_${code}:${stderr.trim().slice(0,1000)}`)));});}

async function nextEvent(client:PoolClient,jobId:string,kind:"status"|"progress"|"completed"|"failed"|"cancelled",data:Record<string,unknown>){const sequence=await client.query<{sequence:number}>("SELECT coalesce(max(sequence),0)::int+1 AS sequence FROM system_job_events WHERE job_id=$1",[jobId]);await client.query("INSERT INTO system_job_events(job_id,sequence,kind,data) VALUES ($1,$2,$3,$4::jsonb)",[jobId,sequence.rows[0].sequence,kind,JSON.stringify(data)]);}

async function claim(){const client=await pool.connect();try{await client.query("BEGIN");const selected=await client.query<Job>("SELECT * FROM system_jobs WHERE status='queued' AND kind IN ('backup_create','backup_verify','restore_plan','restore_apply') ORDER BY created_at,id FOR UPDATE SKIP LOCKED LIMIT 1");const job=selected.rows[0];if(!job){await client.query("COMMIT");return null;}const updated=await client.query<Job>("UPDATE system_jobs SET status='running',stage='claimed_by_maintenance_worker',progress=0.02,attempts=attempts+1,started_at=coalesce(started_at,now()),updated_at=now() WHERE id=$1 RETURNING *",[job.id]);await nextEvent(client,job.id,"status",{status:"running",stage:"claimed_by_maintenance_worker"});await client.query("COMMIT");return updated.rows[0];}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}

async function complete(job:Job,result:Record<string,unknown>,stage:string){const client=await pool.connect();try{await client.query("BEGIN");await client.query("UPDATE system_jobs SET status='succeeded',stage=$2,progress=1,result=$3::jsonb,error_code=NULL,safe_error_detail=NULL,retryable=false,finished_at=now(),updated_at=now() WHERE id=$1",[job.id,stage,JSON.stringify(result)]);await nextEvent(client,job.id,"completed",result);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}

async function fail(job:Job,code:string,detail:string,retryable:boolean){const client=await pool.connect();try{await client.query("BEGIN");await client.query("UPDATE system_jobs SET status='failed',stage='failed',progress=NULL,error_code=$2,safe_error_detail=$3,retryable=$4,finished_at=now(),updated_at=now() WHERE id=$1",[job.id,code,detail,retryable]);if(job.kind==="backup_create"&&job.input.backupId)await client.query("UPDATE backups SET state='failed',updated_at=now() WHERE id=$1 AND owner_id=$2",[job.input.backupId,job.owner_id]);await nextEvent(client,job.id,"failed",{code,detail,retryable});await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
async function cancel(job:Job){const client=await pool.connect();try{await client.query("BEGIN");await client.query("UPDATE system_jobs SET status='cancelled',stage='cancelled_at_safe_checkpoint',progress=NULL,retryable=false,finished_at=now(),updated_at=now() WHERE id=$1",[job.id]);if(job.kind==="backup_create"&&job.input.backupId)await client.query("UPDATE backups SET state='failed',updated_at=now() WHERE id=$1 AND owner_id=$2",[job.input.backupId,job.owner_id]);await nextEvent(client,job.id,"cancelled",{code:"cancelled",detail:"Cancelled at a safe maintenance checkpoint.",retryable:false});await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
async function throwIfCancelled(jobId:string){const state=await pool.query<{cancel_requested:boolean}>("SELECT cancel_requested FROM system_jobs WHERE id=$1",[jobId]);if(state.rows[0]?.cancel_requested)throw new Error("maintenance_job_cancelled");}

async function extractRegisteredBackup(backupId:string,ownerId:string){const result=await pool.query<Record<string,unknown>>("SELECT b.*,d.storage_root FROM backups b JOIN backup_destinations d ON d.id=b.destination_id WHERE b.id=$1 AND b.owner_id=$2",[backupId,ownerId]);const backup=result.rows[0];if(!backup)throw new Error("backup_not_found");const root=path.resolve(String(backup.storage_root)),bundle=safeChild(root,String(backup.bundle_path));if(!existsSync(bundle)||await sha256File(bundle)!==backup.bundle_sha256)throw new Error("backup_bundle_integrity_failure");const temporary=await mkdtemp(path.join(os.tmpdir(),"sorta-omega-verify-")),zip=path.join(temporary,"bundle.zip"),extracted=path.join(temporary,"bundle");await mkdir(extracted);await writeFile(zip,decryptBackup(await readFile(bundle),encryptionKey));await run("tar.exe",["-xf",zip,"-C",extracted]);const manifest=await validateExtractedBackup(extracted);return{backup,root,bundle,temporary,extracted,manifest};}

async function createBackup(job:Job){const backupId=String(job.input.backupId??""),result=await pool.query<Record<string,unknown>>("SELECT b.*,d.storage_root,d.encryption_profile_id AS destination_encryption_profile_id FROM backups b JOIN backup_destinations d ON d.id=b.destination_id WHERE b.id=$1 AND b.owner_id=$2 AND b.system_job_id=$3",[backupId,job.owner_id,job.id]),backup=result.rows[0];if(!backup)throw new Error("backup_registry_mismatch");if(backup.encryption_profile_id!=="aes-256-gcm-host-v1"||backup.destination_encryption_profile_id!==backup.encryption_profile_id)throw new Error("unsupported_backup_encryption_profile");const root=path.resolve(String(backup.storage_root));await mkdir(root,{recursive:true});const staging=safeChild(root,path.join(".omega-staging",job.id));await mkdir(staging,{recursive:true});try{await throwIfCancelled(job.id);await pool.query("UPDATE backups SET state='creating',updated_at=now() WHERE id=$1",[backupId]);const output=await run("powershell.exe",["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File",backupScript,"-Destination",staging]),bundleDirectory=output.split(/\r?\n/).at(-1)?.trim();await throwIfCancelled(job.id);if(!bundleDirectory||!existsSync(bundleDirectory))throw new Error("backup_script_did_not_return_bundle");const manifest=await validateExtractedBackup(bundleDirectory),manifestBytes=await readFile(path.join(bundleDirectory,"manifest.json")),manifestSha256=createHash("sha256").update(manifestBytes).digest("hex"),zip=safeChild(staging,`${backupId}.zip`),relativeBundle=path.join("backups",`${backupId}.zip.enc`).replaceAll("\\","/"),encrypted=safeChild(root,relativeBundle);await run("tar.exe",["-a","-c","-f",zip,"-C",bundleDirectory,"."]);await throwIfCancelled(job.id);await writeEncryptedBundle(zip,encrypted,encryptionKey);const bundleSha256=await sha256File(encrypted),byteLength=(await stat(encrypted)).size;await pool.query("UPDATE backups SET state='ready',manifest=$2::jsonb,manifest_sha256=$3,bundle_path=$4,bundle_sha256=$5,byte_length=$6,updated_at=now() WHERE id=$1",[backupId,JSON.stringify(manifest),manifestSha256,relativeBundle,bundleSha256,byteLength]);await complete(job,{type:"backup_created",backupId,manifestSha256,writesApplied:true},"encrypted_bundle_ready");}finally{await rm(staging,{recursive:true,force:true});}}

async function verifyBackup(job:Job){const backupId=String(job.input.backupId??""),extracted=await extractRegisteredBackup(backupId,job.owner_id);try{const verifiedAt=new Date().toISOString();await pool.query("UPDATE backups SET state='ready',verified_at=$3,updated_at=now() WHERE id=$1 AND owner_id=$2",[backupId,job.owner_id,verifiedAt]);await complete(job,{type:"backup_verified",backupId,verifiedAt,complete:true,writesApplied:true},"verification_complete");}finally{await rm(extracted.temporary,{recursive:true,force:true});}}

async function planRestore(job:Job){const backupId=String(job.input.backupId??""),restorePlanId=String(job.input.restorePlanId??""),extracted=await extractRegisteredBackup(backupId,job.owner_id);try{const compatible=extracted.manifest.format==="sorta-omega-backup-v2",compatibility={compatible,format:extracted.manifest.format,validatedDumpAndBlobs:true,externalCredentialsIncluded:false,providerSendsDisabledAfterRestore:true,limitations:["Replacement restore requires the explicit maintenance-mode operator command.","Provider credentials are not restored and must be reauthorized."]};const updated=await pool.query<{plan_revision:number}>("UPDATE restore_plans SET state=$4,compatibility=$5::jsonb,plan_revision=plan_revision+1,updated_at=now() WHERE id=$1 AND owner_id=$2 AND backup_id=$3 RETURNING plan_revision",[restorePlanId,job.owner_id,backupId,compatible?"ready":"incompatible",JSON.stringify(compatibility)]);if(!updated.rows[0])throw new Error("restore_plan_registry_mismatch");await complete(job,{type:"restore_planned",restorePlanId,compatible,planRevision:updated.rows[0].plan_revision,writesApplied:true},"restore_plan_ready");}finally{await rm(extracted.temporary,{recursive:true,force:true});}}

async function processJob(job:Job){if(job.kind==="backup_create")return createBackup(job);if(job.kind==="backup_verify")return verifyBackup(job);if(job.kind==="restore_plan")return planRestore(job);return fail(job,"maintenance_restore_apply_requires_operator","Replacement restore must run through the owner-controlled maintenance command because restoring the database replaces the job registry itself.",false);}

let stopping=false;process.on("SIGINT",()=>stopping=true);process.on("SIGTERM",()=>stopping=true);
if(!existsSync(backupScript))throw new Error("backup_script_not_found");
while(!stopping){const job=await claim();if(!job){await new Promise(resolve=>setTimeout(resolve,maintenanceConfig.SYSTEM_JOB_POLL_MS));continue;}try{await processJob(job);}catch(error){const code=error instanceof Error&&/^[a-z0-9_]+$/.test(error.message)?error.message:"maintenance_job_failed";if(code==="maintenance_job_cancelled"){await cancel(job);continue;}const retryable=job.attempts<job.max_attempts&&["maintenance_job_failed","backup_script_did_not_return_bundle"].includes(code);await fail(job,code,retryable?"The host maintenance operation failed and can be retried.":"The host maintenance operation failed safely; inspect the redacted host service log.",retryable);}}
await pool.end();
