import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import {
  activityEventSchema,
  preferencesSchema,
  updatePreferencesSchema,
  systemStatusSchema,
  vaultSchema,
  createVaultSchema,
  updateVaultSchema,
  purgeRequestSchema,
  createUploadSchema,
  uploadSessionSchema,
  completeUploadSchema,
  blobSummarySchema,
  createExportSchema,
  exportManifestSchema,
  planImportSchema,
  importManifestSchema,
  applyImportSchema,
  aiStatusSchema,
  aiOperationSchema,
  aiTestRequestSchema,
  calendarSchema,
  createCalendarSchema,
  updateCalendarSchema,
  calendarEntitySchema,
  personSummarySchema,
  personContextSchema,
  proposeSocialTimeSchema,
  authorizationRequestSchema,
  reauthorizationRequestSchema,
  authorizationStartSchema,
  calendarEventSchema,
  calendarViewSchema,
  calendarBriefQuerySchema,
  calendarBriefSchema,
  calendarExportInputSchema,
  calendarImportInputSchema,
  previewProviderCalendarActionSchema,
  providerCalendarActionSchema,
  calendarConflictSchema,
  calendarEventRevisionSchema,
  chatMessageAcceptedSchema,
  chatMessageSchema,
  askHandleSchema,
  chatSchema,
  claimWorkerJobRequestSchema,
  commitmentSchema,
  configureWorkerSchema,
  collectionSchema,
  correctNoteClassificationSchema,
  correctionReceiptSchema,
  createCalendarEntitySchema,
  updateCalendarEntitySchema,
  entityAliasSchema,
  addEntityAliasSchema,
  previewEntityMergeSchema,
  calendarPolicySetInputSchema,
  calendarPolicySetSchema,
  policyDryRunInputSchema,
  automationDecisionSchema,
  undoCalendarDecisionSchema,
  calendarDecisionUndoResultSchema,
  createCalendarEventSchema,
  refreshPrivateEventContextSchema,
  setEventReminderPlanSchema,
  eventReminderPlanSchema,
  createCaptureSchema,
  createUrlCaptureSchema,
  generateArtifactSchema,
  captureSchema,
  createNoteSchema,
  createChatMessageSchema,
  createChatSchema,
  createCommitmentSchema,
  updateCommitmentSchema,
  rematchCommitmentSchema,
  commitmentDetailSchema,
  createCollectionSchema,
  createLabelSchema,
  createPrepItemSchema,
  createRoutingRuleSchema,
  createRelationshipSchema,
  createReminderSchema,
  createTaskSchema,
  expectedTaskRevisionSchema,
  updateTaskSchema,
  documentRepresentationSchema,
  editNoteSchema,
  expectedNoteRevisionSchema,
  eventOccurrenceSchema,
  freeBusyQuerySchema,
  freeBusyResultSchema,
  jobHandleSchema,
  jobEventSchema,
  jobSchema,
  systemJobHandleSchema,
  systemJobListSchema,
  systemJobSchema,
  createBackupSchema,
  backupSummarySchema,
  backupManifestSchema,
  createRestorePlanSchema,
  applyRestoreSchema,
  hostResourceReportSchema,
  deploymentProfileSchema,
  checkDeploymentSchema,
  resourcePolicySchema,
  setHostResourcePolicySchema,
  previewRemoteAccessSetupSchema,
  labelSchema,
  indexStatusSchema,
  modelProfileSchema,
  vaultAiPolicySchema,
  aiDisclosurePreviewInputSchema,
  aiDisclosurePreviewSchema,
  setVaultAiPolicySchema,
  passkeyOptionsRequestSchema,
  passkeySummarySchema,
  recoveryCodesSchema,
  recoveryRequestSchema,
  recoverySessionSchema,
  relationshipSchema,
  relatedResultSchema,
  resurfacingFeedbackInputSchema,
  resurfacingFeedbackSchema,
  reprocessNoteSchema,
  restoreNoteRevisionSchema,
  rebuildIndexRequestSchema,
  routingRulePreviewSchema,
  routingRuleSchema,
  rulePreviewResultSchema,
  noteRevisionSchema,
  noteSchema,
  notificationSchema,
  reminderSchema,
  noteOrganizationSchema,
  occurrenceExceptionInputSchema,
  occurrenceExceptionSchema,
  prepItemSchema,
  searchRequestSchema,
  searchResultSchema,
  searchSuggestionsSchema,
  resolvedCitationSchema,
  schoolSubjectSchema,
  createSchoolSubjectSchema,
  schoolCourseSchema,
  courseMaterialLinkSchema,
  linkCourseMaterialSchema,
  archiveSchoolAssignmentOverlaySchema,
  teacherViewSchema,
  schoolReadinessReportSchema,
  createSchoolCourseSchema,
  schoolAssignmentSchema,
  createSchoolAssignmentSchema,
  schoolLessonSchema,
  createSchoolLessonSchema,
  schoolAssessmentSchema,
  createSchoolAssessmentSchema,
  attendanceRecordSchema,
  createAttendanceRecordSchema,
  attendanceSummarySchema,
  createCatchUpPlanSchema,
  previewAttendanceCatchUpSchema,
  catchUpPlanResultSchema,
  performanceGradeSchema,
  createPerformanceGradeSchema,
  gradeRecordSchema,
  createGradeRecordSchema,
  updateGradeRecordSchema,
  archiveGradeRecordSchema,
  performanceTargetSchema,
  setPerformanceTargetSchema,
  performanceSummarySchema,
  generatePerformanceRecommendationsSchema,
  proposeTaskBreakdownSchema,
  studyPlanSchema,
  createStudyPlanSchema,
  updateStudyPlanSchema,
  withdrawStudyPlanSchema,
  studyWithdrawalProposalSchema,
  studySessionSchema,
  createStudySessionSchema,
  studySessionActionSchema,
  taskExecutionHistorySchema,
  startExecutionSessionSchema,
  transitionExecutionSessionSchema,
  executionSessionRecordSchema,
  createSyncSnapshotSchema,
  pushSyncSchema,
  syncBatchSchema,
  syncAckSchema,
  syncSocketClientFrameSchema,
  syncSocketServerFrameSchema,
  syncSnapshotResultSchema,
  vaultChangeEventSchema,
  knowledgeGapSchema,
  createReportedKnowledgeGapSchema,
  updateKnowledgeGapSchema,
  correctKnowledgeGapSchema,
  studyExerciseSchema,
  createStudyExerciseSchema,
  studyAttemptSchema,
  createStudyAttemptSchema,
  requestStudyFeedbackSchema,
  correctStudyFeedbackSchema,
  studyActivitySchema,
  createStudyActivitySchema,
  submitStudyResponseSchema,
  flashcardDeckSchema,
  createFlashcardDeckSchema,
  updateFlashcardDeckSchema,
  flashcardSchema,
  createFlashcardSchema,
  updateFlashcardSchema,
  recordFlashcardReviewSchema,
  reviewFlashcardSchema,
  flashcardReviewReceiptSchema,
  flashcardReviewSchema,
  flashcardReviewItemSchema,
  schedulerPreferencesSchema,
  setSchedulerPreferencesSchema,
  schedulingConstraintsSchema,
  setSchedulingConstraintsSchema,
  proposeScheduleSchema,
  schedulePreviewRequestSchema,
  preparationPlanInputSchema,
  scheduleReplanRequestSchema,
  scheduleExplanationSchema,
  proposalSchema,
  proposalInputSchema,
  previewIdeaPromotionSchema,
  proposeIdeaProjectSchema,
  rejectProposalSchema,
  acceptProposalSchema,
  undoProposalSchema,
  proposalUndoReceiptSchema,
  sessionSummarySchema,
  setNoteLabelsSchema,
  taskSchema,
  projectSchema,createProjectSchema,updateProjectSchema,ideaSchema,createIdeaSchema,updateIdeaSchema,goalSchema,createGoalSchema,updateGoalSchema,memorySchema,createMemorySchema,updateMemorySchema,personalProfileSchema,integrationConnectionSchema,createIntegrationConnectionSchema,integrationCapabilityListSchema,integrationProviderDescriptorSchema,connectorResourceSchema,resourceSelectionSchema,resourceSelectionInputSchema,connectorScheduleSchema,connectorSyncStatusSchema,connectionSyncResultSchema,disconnectIntegrationSchema,previewConnectionDisconnectSchema,connectionDisconnectPreviewSchema,connectionMappingSchema,setConnectionMappingSchema,insightSchema,generateInsightSchema,updateInsightSchema,personalDataItemSchema,personalDataPoliciesSchema,setPersonalDataPoliciesSchema,previewPersonalDataImportSchema,personalDataImportPreviewSchema,applyPersonalDataImportSchema,personalDataImportReceiptSchema,interestSchema,interestEvidenceSchema,refreshPersonalProfileSchema,rebuildPersonalProfileSchema,syncSelectedPersonalDataSchema,updateInterestSchema,decideInterestClaimSchema,
  todaySchema,
  nextActionSetSchema,
  momentumSummarySchema,
  momentumPreferencesSchema,
  updateMomentumPreferencesSchema,
  updateNotificationSchema,
  updateNoteMetadataSchema,
  updateReminderSchema,
  updatePrepItemSchema,
  updateRoutingRuleSchema,
  updateCalendarEventSchema,
  updateCollectionSchema,
  updateLabelSchema,
  updateOccurrenceExceptionSchema,
  updateSchoolSubjectSchema,
  updateSchoolCourseSchema,
  updateSchoolAssignmentSchema,
  updateSchoolLessonSchema,
  updateSchoolAssessmentSchema,
  updateAttendanceRecordSchema,
  updatePerformanceGradeSchema,
  undoAiOperationSchema,
  undoReceiptSchema,
  workerCompleteSchema,
  workerEvidencePacketSchema,
  workerEvidenceRequestSchema,
  workerFailSchema,
  toolDescriptorSchema,
  runDomainToolSchema,
  toolPolicySetSchema,
  setToolPoliciesSchema,
  executeNaturalLanguageCommandSchema,
  sourceObjectSchema,
  sourceObjectDetailSchema,
  refreshSourceObjectSchema,
  sourceExclusionInputSchema,
  sourceExclusionSchema,
  transcriptSchema,
  transcriptAssociationSchema,
  correctTranscriptSchema,
  associateTranscriptSchema,
  analyzeTranscriptSchema,
  schoolOverviewSchema,
  previewSchoolImportSchema,
  applySchoolImportSchema,
  workerHeartbeatRequestSchema,
  workerHeartbeatResponseSchema,
  workerIndexBatchSchema,
  workerJobInputSchema,
  workerLeaseHeartbeatSchema,
  workerLeaseSchema,
  workerProgressEventsSchema,
  workerSourceInputSchema,
  workerSummarySchema
  ,createDevicePairingSchema,devicePairingChallengeSchema,approveDevicePairingSchema,devicePairingApprovalSchema,exchangeDevicePairingSchema,refreshNativeTokenSchema,tokenPairSchema,pairingPendingSchema,deviceSummarySchema,createApiTokenSchema,apiTokenSummarySchema,apiTokenCreatedSchema,deviceCachePolicySchema,setDeviceCachePolicySchema,requestDeviceCachePurgeSchema,cachePurgeRequestSchema
} from "./index.js";
import { httpOperations } from "./http-operations.js";

const sessionSchema = z.object({
  id: z.string().uuid(), owner_id: z.string().uuid(), expires_at: z.string().datetime(), auth_level: z.enum(["passkey", "recovery"])
});
const webAuthnOptionsSchema = z.object({
  challenge_id: z.string().uuid(), public_key_options: z.record(z.unknown()), expires_at: z.string().datetime()
});
const schemaMap: Record<string, z.ZodTypeAny> = {
  Health: z.object({ status: z.enum(["ok", "ready"]) }),
  Meta: z.object({ api_version: z.string(), client_min_version: z.string(), schema_version: z.number().int() }),
  Preferences: preferencesSchema,
  UpdatePreferences: updatePreferencesSchema,
  SystemStatus: systemStatusSchema,
  Vault: vaultSchema,
  VaultList: z.object({ items: z.array(vaultSchema) }),
  CreateVault: createVaultSchema,
  UpdateVault: updateVaultSchema,
  PurgeRequest:purgeRequestSchema,
  CreateUpload: createUploadSchema,
  UploadSession: uploadSessionSchema,
  CompleteUpload: completeUploadSchema,
  BlobSummary: blobSummarySchema,
  CreateExport:createExportSchema,
  ExportManifest:exportManifestSchema,
  PlanImport:planImportSchema,
  ImportManifest:importManifestSchema,
  ApplyImport:applyImportSchema,
  BootstrapOptionsInput: z.object({ bootstrap_secret: z.string().min(1), owner_label: z.string().min(1).max(120) }),
  WebAuthnOptions: webAuthnOptionsSchema,
  WebAuthnVerifyInput: z.object({ challenge_id: z.string().uuid(), credential: z.record(z.unknown()) }),
  BootstrapResult: z.object({ owner: z.object({ id: z.string().uuid(), label: z.string() }), recovery_codes_once: z.array(z.string()), session: sessionSchema }),
  Session: sessionSchema,
  Note: noteSchema,
  NoteList: z.object({ items: z.array(noteSchema) }),
  UpdateNoteMetadata: updateNoteMetadataSchema,
  DocumentRepresentation: documentRepresentationSchema,
  EditNote: editNoteSchema,
  ReprocessNote: reprocessNoteSchema,
  NoteRevision: noteRevisionSchema,
  NoteRevisionList: z.object({ items: z.array(noteRevisionSchema) }),
  CorrectNoteClassification: correctNoteClassificationSchema,
  CorrectionReceipt: correctionReceiptSchema,
  Label: labelSchema,
  LabelList: z.object({ items: z.array(labelSchema) }),
  CreateLabel: createLabelSchema,
  UpdateLabel: updateLabelSchema,
  SetNoteLabels: setNoteLabelsSchema,
  NoteOrganization: noteOrganizationSchema,
  Collection: collectionSchema,
  CollectionList: z.object({ items: z.array(collectionSchema) }),
  CreateCollection: createCollectionSchema,
  UpdateCollection: updateCollectionSchema,
  CollectionItems: z.object({ collection: collectionSchema, items: z.array(noteSchema), nextCursor: z.string().nullable() }),
  RoutingRule: routingRuleSchema,
  RoutingRuleList: z.object({ items: z.array(routingRuleSchema) }),
  CreateRoutingRule: createRoutingRuleSchema,
  UpdateRoutingRule: updateRoutingRuleSchema,
  RoutingRulePreview: routingRulePreviewSchema,
  RulePreviewResult: rulePreviewResultSchema,
  Relationship: relationshipSchema,
  RelationshipList: z.object({ items: z.array(relationshipSchema) }),
  RelatedResult:relatedResultSchema,
  ResurfacingFeedbackInput:resurfacingFeedbackInputSchema,
  ResurfacingFeedback:resurfacingFeedbackSchema,
  CreateRelationship: createRelationshipSchema,
  CreateCapture: createCaptureSchema,
  CreateUrlCapture: createUrlCaptureSchema,
  GenerateArtifact: generateArtifactSchema,
  Capture: captureSchema,
  CreateNote: createNoteSchema,
  ExpectedNoteRevision: expectedNoteRevisionSchema,
  RestoreNoteRevision: restoreNoteRevisionSchema,
  Task: taskSchema,
  Project:projectSchema,ProjectList:z.object({items:z.array(projectSchema),nextCursor:z.string().nullable()}),CreateProject:createProjectSchema,UpdateProject:updateProjectSchema,
  Idea:ideaSchema,IdeaList:z.object({items:z.array(ideaSchema),nextCursor:z.string().nullable()}),CreateIdea:createIdeaSchema,UpdateIdea:updateIdeaSchema,
  Goal:goalSchema,GoalList:z.object({items:z.array(goalSchema),nextCursor:z.string().nullable()}),CreateGoal:createGoalSchema,UpdateGoal:updateGoalSchema,
  Memory:memorySchema,MemoryList:z.object({items:z.array(memorySchema),nextCursor:z.string().nullable()}),CreateMemory:createMemorySchema,UpdateMemory:updateMemorySchema,PersonalProfile:personalProfileSchema,
  IntegrationConnection:integrationConnectionSchema,IntegrationConnectionList:z.object({items:z.array(integrationConnectionSchema),nextCursor:z.string().nullable()}),CreateIntegrationConnection:createIntegrationConnectionSchema,IntegrationCapabilityList:integrationCapabilityListSchema,IntegrationProviderDescriptorList:z.object({items:z.array(integrationProviderDescriptorSchema)}),ConnectorResourceList:z.object({items:z.array(connectorResourceSchema),nextCursor:z.string().nullable()}),ResourceSelection:resourceSelectionSchema,ResourceSelectionInput:resourceSelectionInputSchema,ConnectorSchedule:connectorScheduleSchema,ConnectorSyncStatus:connectorSyncStatusSchema,ConnectionSyncResult:connectionSyncResultSchema,DisconnectIntegration:disconnectIntegrationSchema,PreviewConnectionDisconnect:previewConnectionDisconnectSchema,ConnectionDisconnectPreview:connectionDisconnectPreviewSchema,ConnectionMapping:connectionMappingSchema,SetConnectionMapping:setConnectionMappingSchema,RebuildPersonalProfile:rebuildPersonalProfileSchema,SyncSelectedPersonalData:syncSelectedPersonalDataSchema,
  Insight:insightSchema,InsightList:z.object({items:z.array(insightSchema),nextCursor:z.string().nullable()}),GenerateInsight:generateInsightSchema,UpdateInsight:updateInsightSchema,
  PersonalDataItem:personalDataItemSchema,PersonalDataItemList:z.object({items:z.array(personalDataItemSchema),nextCursor:z.string().nullable()}),PersonalDataPolicies:personalDataPoliciesSchema,SetPersonalDataPolicies:setPersonalDataPoliciesSchema,PreviewPersonalDataImport:previewPersonalDataImportSchema,PersonalDataImportPreview:personalDataImportPreviewSchema,ApplyPersonalDataImport:applyPersonalDataImportSchema,PersonalDataImportReceipt:personalDataImportReceiptSchema,
  Interest:interestSchema,InterestList:z.object({items:z.array(interestSchema),nextCursor:z.string().nullable()}),InterestEvidence:interestEvidenceSchema,InterestEvidenceList:z.object({items:z.array(interestEvidenceSchema),nextCursor:z.string().nullable()}),RefreshPersonalProfile:refreshPersonalProfileSchema,UpdateInterest:updateInterestSchema,DecideInterestClaim:decideInterestClaimSchema,
  TaskList: z.object({ items: z.array(taskSchema) }),
  CreateTask: createTaskSchema,
  UpdateTask: updateTaskSchema,
  ExpectedTaskRevision: expectedTaskRevisionSchema,
  Reminder:reminderSchema,ReminderList:z.object({items:z.array(reminderSchema),nextCursor:z.string().nullable()}),CreateReminder:createReminderSchema,UpdateReminder:updateReminderSchema,
  Notification:notificationSchema,NotificationList:z.object({items:z.array(notificationSchema),nextCursor:z.string().nullable()}),UpdateNotification:updateNotificationSchema,
  CalendarEntity: calendarEntitySchema,
  PersonSummary:personSummarySchema,
  PersonSummaryList:z.object({items:z.array(personSummarySchema),nextCursor:z.string().nullable()}),
  PersonContext:personContextSchema,
  ProposeSocialTime:proposeSocialTimeSchema,
  AuthorizationRequest:authorizationRequestSchema,
  ReauthorizationRequest:reauthorizationRequestSchema,
  AuthorizationStart:authorizationStartSchema,
  CalendarEntityList: z.object({ items: z.array(calendarEntitySchema) }),
  CreateCalendarEntity: createCalendarEntitySchema,
  UpdateCalendarEntity: updateCalendarEntitySchema,
  EntityAlias: entityAliasSchema,
  AddEntityAlias: addEntityAliasSchema,
  PreviewEntityMerge: previewEntityMergeSchema,
  Calendar: calendarSchema,
  CalendarList: z.object({items:z.array(calendarSchema),nextCursor:z.string().nullable()}),
  CreateCalendar: createCalendarSchema,
  UpdateCalendar: updateCalendarSchema,
  CalendarPolicySetInput: calendarPolicySetInputSchema,
  CalendarPolicySet: calendarPolicySetSchema,
  PolicyDryRunInput: policyDryRunInputSchema,
  AutomationDecisionList: z.object({items:z.array(automationDecisionSchema),nextCursor:z.string().nullable()}),
  UndoCalendarDecision: undoCalendarDecisionSchema,
  CalendarDecisionUndoResult: calendarDecisionUndoResultSchema,
  Commitment: commitmentSchema,
  CommitmentList: z.object({ items: z.array(commitmentSchema) }),
  CreateCommitment: createCommitmentSchema,
  UpdateCommitment: updateCommitmentSchema,
  RematchCommitment: rematchCommitmentSchema,
  CommitmentDetail: commitmentDetailSchema,
  CalendarEvent: calendarEventSchema,
  CalendarView: calendarViewSchema,
  CalendarBriefQuery:calendarBriefQuerySchema,
  CalendarBrief:calendarBriefSchema,
  CalendarExportInput:calendarExportInputSchema,
  CalendarImportInput:calendarImportInputSchema,
  PreviewProviderCalendarAction:previewProviderCalendarActionSchema,ProviderCalendarAction:providerCalendarActionSchema,ProviderCalendarActionList:z.object({items:z.array(providerCalendarActionSchema),nextCursor:z.string().nullable()}),
  CalendarEventList: z.object({ items: z.array(calendarEventSchema) }),
  CreateCalendarEvent: createCalendarEventSchema,
  UpdateCalendarEvent: updateCalendarEventSchema,
  CalendarEventRevisionList: z.object({ items: z.array(calendarEventRevisionSchema) }),
  EventOccurrenceList: z.object({ items: z.array(eventOccurrenceSchema) }),
  OccurrenceExceptionInput: occurrenceExceptionInputSchema,
  OccurrenceException: occurrenceExceptionSchema,
  UpdateOccurrenceException: updateOccurrenceExceptionSchema,
  FreeBusyQuery: freeBusyQuerySchema,
  FreeBusyResult: freeBusyResultSchema,
  CalendarConflictList: z.object({ items: z.array(calendarConflictSchema) }),
  PrivateEventContext: z.object({ event: calendarEventSchema, privateContext: z.string().nullable(), prepItems: z.array(prepItemSchema), linkedCommitments: z.array(commitmentSchema) }),
  RefreshPrivateEventContext:refreshPrivateEventContextSchema,
  SetEventReminderPlan:setEventReminderPlanSchema,
  EventReminderPlan:eventReminderPlanSchema,
  PrepItem: prepItemSchema,
  CreatePrepItem: createPrepItemSchema,
  UpdatePrepItem: updatePrepItemSchema,
  SearchRequest: searchRequestSchema,
  SearchResponse: z.union([searchResultSchema, jobHandleSchema]),
  Chat: chatSchema,
  ChatList: z.object({ items: z.array(chatSchema) }),
  CreateChat: createChatSchema,
  ChatMessageList: z.object({ items: z.array(chatMessageSchema), nextCursor:z.string().nullable() }),
  CreateChatMessage: createChatMessageSchema,
  ChatMessageAccepted: chatMessageAcceptedSchema,
  AskHandle:askHandleSchema,
  SearchSuggestions:searchSuggestionsSchema,
  ResolvedCitation:resolvedCitationSchema,
  Job: jobSchema,
  JobHandle: jobHandleSchema,
  JobList: z.object({ items: z.array(jobSchema) }),
  JobEvent: jobEventSchema,
  SystemJobHandle:systemJobHandleSchema,
  SystemJobList:systemJobListSchema,
  SystemJob:systemJobSchema,
  CreateBackup:createBackupSchema,
  BackupSummary:backupSummarySchema,
  BackupList:z.object({items:z.array(backupSummarySchema),nextCursor:z.string().nullable()}),
  BackupManifest:backupManifestSchema,
  CreateRestorePlan:createRestorePlanSchema,
  ApplyRestore:applyRestoreSchema,
  HostResourceReport:hostResourceReportSchema,
  DeploymentProfile:deploymentProfileSchema,
  CheckDeployment:checkDeploymentSchema,
  ResourcePolicy:resourcePolicySchema,
  SetHostResourcePolicy:setHostResourcePolicySchema,
  PreviewRemoteAccessSetup:previewRemoteAccessSetupSchema,
  ToolDescriptorList:z.object({items:z.array(toolDescriptorSchema),nextCursor:z.null()}),
  RunDomainTool:runDomainToolSchema,
  ToolPolicySet:toolPolicySetSchema,
  SetToolPolicies:setToolPoliciesSchema,
  ExecuteNaturalLanguageCommand:executeNaturalLanguageCommandSchema,
  SourceObjectList:z.object({items:z.array(sourceObjectSchema),nextCursor:z.string().nullable()}),
  SourceObjectDetail:sourceObjectDetailSchema,
  RefreshSourceObject:refreshSourceObjectSchema,
  SourceExclusionInput:sourceExclusionInputSchema,
  SourceExclusion:sourceExclusionSchema,
  Transcript:transcriptSchema,
  TranscriptList:z.object({items:z.array(transcriptSchema),nextCursor:z.string().nullable()}),
  TranscriptAssociation:transcriptAssociationSchema,
  CorrectTranscript:correctTranscriptSchema,
  AssociateTranscript:associateTranscriptSchema,
  AnalyzeTranscript:analyzeTranscriptSchema,
  SchoolOverview:schoolOverviewSchema,
  PreviewSchoolImport:previewSchoolImportSchema,
  ApplySchoolImport:applySchoolImportSchema,
  AiStatus: aiStatusSchema,
  VaultAiPolicy:vaultAiPolicySchema,
  AiDisclosurePreviewInput:aiDisclosurePreviewInputSchema,
  AiDisclosurePreview:aiDisclosurePreviewSchema,
  SetVaultAiPolicy:setVaultAiPolicySchema,
  AiTestRequest: aiTestRequestSchema,
  AiOperation: aiOperationSchema,
  AiOperationList: z.object({ items: z.array(aiOperationSchema) }),
  UndoAiOperation: undoAiOperationSchema,
  UndoReceipt: undoReceiptSchema,
  ActivityEventList: z.object({ items: z.array(activityEventSchema), nextCursor: z.string().nullable() }),
  SchoolSubject: schoolSubjectSchema,
  SchoolSubjectList: z.object({ items: z.array(schoolSubjectSchema), nextCursor: z.string().nullable() }),
  CreateSchoolSubject: createSchoolSubjectSchema,
  UpdateSchoolSubject: updateSchoolSubjectSchema,
  SchoolCourse: schoolCourseSchema,
  SchoolCourseList: z.object({ items: z.array(schoolCourseSchema), nextCursor: z.string().nullable() }),
  TeacherViewList:z.object({items:z.array(teacherViewSchema),nextCursor:z.string().nullable()}),
  SchoolReadinessReport:schoolReadinessReportSchema,
  CreateSchoolCourse: createSchoolCourseSchema,
  UpdateSchoolCourse: updateSchoolCourseSchema,
  CourseMaterialLink:courseMaterialLinkSchema,
  CourseMaterialLinkList:z.object({items:z.array(courseMaterialLinkSchema),nextCursor:z.string().nullable()}),
  LinkCourseMaterial:linkCourseMaterialSchema,
  ArchiveSchoolAssignmentOverlay:archiveSchoolAssignmentOverlaySchema,
  SchoolAssignment: schoolAssignmentSchema,
  SchoolAssignmentList: z.object({ items: z.array(schoolAssignmentSchema), nextCursor: z.string().nullable() }),
  CreateSchoolAssignment: createSchoolAssignmentSchema,
  UpdateSchoolAssignment: updateSchoolAssignmentSchema,
  SchoolLesson: schoolLessonSchema,
  SchoolLessonList: z.object({ items: z.array(schoolLessonSchema), nextCursor: z.string().nullable() }),
  CreateSchoolLesson: createSchoolLessonSchema,
  UpdateSchoolLesson: updateSchoolLessonSchema,
  SchoolAssessment: schoolAssessmentSchema,
  SchoolAssessmentList: z.object({ items: z.array(schoolAssessmentSchema), nextCursor: z.string().nullable() }),
  CreateSchoolAssessment: createSchoolAssessmentSchema,
  UpdateSchoolAssessment: updateSchoolAssessmentSchema,
  AttendanceRecord: attendanceRecordSchema,
  AttendanceRecordList: z.object({ items: z.array(attendanceRecordSchema), nextCursor: z.string().nullable() }),
  CreateAttendanceRecord: createAttendanceRecordSchema,
  UpdateAttendanceRecord: updateAttendanceRecordSchema,
  AttendanceSummary: attendanceSummarySchema,
  CreateCatchUpPlan: createCatchUpPlanSchema,
  PreviewAttendanceCatchUp:previewAttendanceCatchUpSchema,
  CatchUpPlanResult: catchUpPlanResultSchema,
  PerformanceGrade: performanceGradeSchema,
  PerformanceGradeList: z.object({ items: z.array(performanceGradeSchema), nextCursor: z.string().nullable() }),
  CreatePerformanceGrade: createPerformanceGradeSchema,
  UpdatePerformanceGrade: updatePerformanceGradeSchema,
  GradeRecord:gradeRecordSchema,
  GradeRecordList:z.object({items:z.array(gradeRecordSchema),nextCursor:z.string().nullable()}),
  CreateGradeRecord:createGradeRecordSchema,
  UpdateGradeRecord:updateGradeRecordSchema,
  ArchiveGradeRecord:archiveGradeRecordSchema,
  PerformanceTarget: performanceTargetSchema,
  PerformanceTargetList: z.object({ items: z.array(performanceTargetSchema), nextCursor: z.string().nullable() }),
  SetPerformanceTarget: setPerformanceTargetSchema,
  PerformanceSummary: performanceSummarySchema,
  GeneratePerformanceRecommendations:generatePerformanceRecommendationsSchema,
  ProposeTaskBreakdown:proposeTaskBreakdownSchema,
  StudyPlan: studyPlanSchema,
  StudyPlanList: z.object({ items: z.array(studyPlanSchema), nextCursor: z.string().nullable() }),
  CreateStudyPlan: createStudyPlanSchema,
  UpdateStudyPlan: updateStudyPlanSchema,
  WithdrawStudyPlan:withdrawStudyPlanSchema,
  StudyWithdrawalProposal:studyWithdrawalProposalSchema,
  StudySession: studySessionSchema,
  StudySessionList: z.object({ items: z.array(studySessionSchema), nextCursor: z.string().nullable() }),
  CreateStudySession: createStudySessionSchema,
  StudySessionAction: studySessionActionSchema,
  TaskExecutionHistory: taskExecutionHistorySchema,
  StartExecutionSession:startExecutionSessionSchema,
  TransitionExecutionSession:transitionExecutionSessionSchema,
  ExecutionSession:executionSessionRecordSchema,
  CreateSyncSnapshot: createSyncSnapshotSchema,
  PushSync: pushSyncSchema,
  SyncBatch: syncBatchSchema,
  SyncAck: syncAckSchema,
  SyncSocketClientFrame: syncSocketClientFrameSchema,
  SyncSocketServerFrame: syncSocketServerFrameSchema,
  SyncSnapshotResult: syncSnapshotResultSchema,
  VaultChangeEvent: vaultChangeEventSchema,
  KnowledgeGap: knowledgeGapSchema,
  KnowledgeGapList: z.object({ items: z.array(knowledgeGapSchema), nextCursor: z.string().nullable() }),
  CreateReportedKnowledgeGap: createReportedKnowledgeGapSchema,
  UpdateKnowledgeGap: updateKnowledgeGapSchema,
  CorrectKnowledgeGap: correctKnowledgeGapSchema,
  StudyExercise: studyExerciseSchema,
  StudyExerciseList: z.object({ items: z.array(studyExerciseSchema), nextCursor: z.string().nullable() }),
  CreateStudyExercise: createStudyExerciseSchema,
  StudyAttempt: studyAttemptSchema,
  StudyAttemptList: z.object({ items: z.array(studyAttemptSchema), nextCursor: z.string().nullable() }),
  CreateStudyAttempt: createStudyAttemptSchema,
  RequestStudyFeedback: requestStudyFeedbackSchema,
  CorrectStudyFeedback: correctStudyFeedbackSchema,
  StudyActivity:studyActivitySchema,
  StudyActivityList:z.object({items:z.array(studyActivitySchema),nextCursor:z.string().nullable()}),
  CreateStudyActivity:createStudyActivitySchema,
  SubmitStudyResponse:submitStudyResponseSchema,
  FlashcardDeck: flashcardDeckSchema,
  FlashcardDeckList: z.object({ items: z.array(flashcardDeckSchema), nextCursor: z.string().nullable() }),
  CreateFlashcardDeck: createFlashcardDeckSchema,
  UpdateFlashcardDeck: updateFlashcardDeckSchema,
  Flashcard: flashcardSchema,
  FlashcardList: z.object({ items: z.array(flashcardSchema), nextCursor: z.string().nullable() }),
  CreateFlashcard: createFlashcardSchema,
  UpdateFlashcard: updateFlashcardSchema,
  FlashcardReviewQueue: z.object({ items: z.array(flashcardReviewItemSchema), at: z.string().datetime() }),
  RecordFlashcardReview: recordFlashcardReviewSchema,
  ReviewFlashcard: reviewFlashcardSchema,
  FlashcardReviewReceipt: flashcardReviewReceiptSchema,
  FlashcardReview: flashcardReviewSchema,
  SchedulerPreferences: schedulerPreferencesSchema,
  SetSchedulerPreferences: setSchedulerPreferencesSchema,
  SchedulingConstraints:schedulingConstraintsSchema,
  SetSchedulingConstraints:setSchedulingConstraintsSchema,
  ProposeSchedule:proposeScheduleSchema,
  SchedulePreviewRequest: schedulePreviewRequestSchema,
  PreparationPlanInput:preparationPlanInputSchema,
  ScheduleReplanRequest: scheduleReplanRequestSchema,
  ScheduleExplanation: scheduleExplanationSchema,
  Proposal: proposalSchema,
  ProposalList: z.object({ items: z.array(proposalSchema), nextCursor: z.string().nullable() }),
  ProposalInput: proposalInputSchema,
  PreviewIdeaPromotion: previewIdeaPromotionSchema,
  ProposeIdeaProject: proposeIdeaProjectSchema,
  RejectProposal: rejectProposalSchema,
  AcceptProposal: acceptProposalSchema,
  UndoProposal: undoProposalSchema,
  ProposalUndoReceipt: proposalUndoReceiptSchema,
  ModelProfileList: z.object({ items: z.array(modelProfileSchema) }),
  IndexStatus: indexStatusSchema,
  RebuildIndexRequest: rebuildIndexRequestSchema,
  RecoveryRequest: recoveryRequestSchema,
  RecoverySession: recoverySessionSchema,
  PasskeySummary: passkeySummarySchema,
  PasskeyList: z.object({ items: z.array(passkeySummarySchema) }),
  PasskeyOptionsRequest: passkeyOptionsRequestSchema,
  RecoveryCodes: recoveryCodesSchema,
  SessionSummaryList: z.object({ items: z.array(sessionSummarySchema) }),
  CreateDevicePairing:createDevicePairingSchema,DevicePairingChallenge:devicePairingChallengeSchema,ApproveDevicePairing:approveDevicePairingSchema,DevicePairingApproval:devicePairingApprovalSchema,ExchangeDevicePairing:exchangeDevicePairingSchema,RefreshNativeToken:refreshNativeTokenSchema,TokenPair:tokenPairSchema,PairingExchangeResult:z.union([tokenPairSchema,pairingPendingSchema]),DeviceList:z.object({items:z.array(deviceSummarySchema)}),DeviceCachePolicy:deviceCachePolicySchema,SetDeviceCachePolicy:setDeviceCachePolicySchema,RequestDeviceCachePurge:requestDeviceCachePurgeSchema,CachePurgeRequest:cachePurgeRequestSchema,CreateApiToken:createApiTokenSchema,ApiTokenSummary:apiTokenSummarySchema,ApiTokenCreated:apiTokenCreatedSchema,ApiTokenList:z.object({items:z.array(apiTokenSummarySchema)}),
  Today: todaySchema,
  NextActionSet: nextActionSetSchema,
  MomentumSummary: momentumSummarySchema,
  MomentumPreferences: momentumPreferencesSchema,
  UpdateMomentumPreferences: updateMomentumPreferencesSchema,
  WorkerHeartbeatRequest: workerHeartbeatRequestSchema,
  WorkerHeartbeatResponse: workerHeartbeatResponseSchema,
  ClaimWorkerJobRequest: claimWorkerJobRequestSchema,
  WorkerLease: workerLeaseSchema,
  WorkerJobInput: workerJobInputSchema,
  WorkerSourceInput: workerSourceInputSchema,
  WorkerEvidenceRequest: workerEvidenceRequestSchema,
  WorkerEvidencePacket: workerEvidencePacketSchema,
  WorkerIndexBatch: workerIndexBatchSchema,
  IndexBatchAck: z.object({ acceptedChunks: z.number().int().nonnegative() }),
  WorkerLeaseHeartbeat: workerLeaseHeartbeatSchema,
  LeaseState: z.object({ expiresAt: z.string().datetime(), cancelRequested: z.boolean() }),
  WorkerProgressEvents: workerProgressEventsSchema,
  EventAck: z.object({ acceptedSequence: z.number().int().nonnegative() }),
  WorkerComplete: workerCompleteSchema,
  WorkerFail: workerFailSchema,
  WorkerSummary: workerSummarySchema,
  WorkerList: z.object({ items: z.array(workerSummarySchema) }),
  ConfigureWorker: configureWorkerSchema
};

function schemaRef(name: string) {
  return { $ref: `#/components/schemas/${name}` };
}

const paths: Record<string, Record<string, unknown>> = {};
for (const operation of httpOperations) {
  const parameters = [...operation.path.matchAll(/\{([^}]+)\}/g)].map((match) => ({
    name: match[1], in: "path", required: true,
    schema: match[1] === "passkeyId" ? { type: "string" } : match[1] === "providerId" ? { type:"string",enum:["microsoft","google_calendar"] } : match[1] === "partNumber" ? { type: "integer", minimum: 1, maximum: 512 } : { type: "string", format: "uuid" }
  }));
  if (operation.operationId === "putUploadPart") parameters.push(
    { name: "content-range", in: "header", required: true, schema: { type: "string" } } as never,
    { name: "x-part-sha256", in: "header", required: true, schema: { type: "string", pattern: "^[0-9a-f]{64}$" } } as never
  );
  if (operation.operationId === "getBlobContent") parameters.push(
    { name: "download", in: "query", required: false, schema: { type: "boolean" } } as never,
    { name: "range", in: "header", required: false, schema: { type: "string", pattern: "^bytes=" } } as never,
    { name: "x-job-id", in: "header", required: false, schema: { type: "string", format: "uuid" } } as never,
    { name: "x-job-lease-token", in: "header", required: false, schema: { type: "string" } } as never
  );
  const successes = Array.isArray(operation.success) ? operation.success : [operation.success];
  const responses: Record<string, unknown> = {
    "400": { $ref: "#/components/responses/BadRequest" },
    "500": { $ref: "#/components/responses/InternalError" }
  };
  for (const status of successes) {
    responses[String(status)] = status === 204
      ? { description: "No content" }
      : { description: "Success", content: { [operation.responseMediaType ?? "application/json"]: { schema: operation.responseSchema ? schemaRef(operation.responseSchema) : {} } } };
  }
  if (!operation.public) responses["401"] = { $ref: "#/components/responses/Unauthorized" };
  paths[operation.path] ??= {};
  paths[operation.path][operation.method] = {
    operationId: operation.operationId,
    tags: [operation.tag],
    parameters,
    security: operation.public ? [] : operation.path.startsWith("/api/v1/vaults/") ? [{ cookieAuth: [] }, { bearerAuth: [] }] : [{ cookieAuth: [] }],
    ...(operation.requestSchema ? { requestBody: { required: true, content: { "application/json": { schema: schemaRef(operation.requestSchema) } } } } : operation.requestMediaType ? { requestBody: { required: true, content: { [operation.requestMediaType]: { schema: { type: "string", format: "binary" } } } } } : {}),
    responses
  };
}

const schemas = Object.fromEntries(Object.entries(schemaMap).map(([name, schema]) => {
  const json = zodToJsonSchema(schema, { target: "openApi3", $refStrategy: "none" }) as Record<string, unknown>;
  delete json.$schema;
  return [name, json];
}));

const document = {
  openapi: "3.1.0",
  info: {
    title: "Sorta Omega implemented API",
    version: "0.1.0",
    description: "Generated from the implemented operation registry. Planned master-spec operations are intentionally absent until implemented."
  },
  servers: [{ url: "/", description: "Configured canonical origin" }],
  paths,
  components: {
    securitySchemes: { cookieAuth: { type: "apiKey", in: "cookie", name: "__Host-sorta_session" }, bearerAuth: { type: "http", scheme: "bearer" } },
    schemas,
    responses: {
      BadRequest: { description: "Request validation failed", content: { "application/json": { schema: { type: "object", properties: { error: { type: "string" } }, required: ["error"] } } } },
      Unauthorized: { description: "Authentication required", content: { "application/json": { schema: { type: "object", properties: { error: { const: "authentication_required" } }, required: ["error"] } } } },
      InternalError: { description: "Internal error", content: { "application/json": { schema: { type: "object", properties: { error: { const: "internal_error" } }, required: ["error"] } } } }
    }
  }
};

const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
const outputPath = path.resolve(currentDirectory, "../../../docs/openapi.json");
const inventoryPath = path.resolve(currentDirectory, "../../../docs/API-INVENTORY.json");
const generated=`${JSON.stringify(document, null, 2)}\n`;
const inventoryGenerated=`${JSON.stringify({
  generatedFrom:"packages/contracts/src/http-operations.ts",
  operationCount:httpOperations.length,
  operations:httpOperations.map(operation=>({
    operationId:operation.operationId,
    method:operation.method.toUpperCase(),
    path:operation.path,
    tag:operation.tag,
    authentication:operation.public?"public":"required",
    success:operation.success,
    requestSchema:operation.requestSchema??null,
    responseSchema:operation.responseSchema??null
  }))
},null,2)}\n`;
if(process.argv.includes("--check")){
  const current=await readFile(outputPath,"utf8").catch(()=>"");
  const currentInventory=await readFile(inventoryPath,"utf8").catch(()=>"");
  if(current!==generated){console.error(`OpenAPI artifact is stale: ${outputPath}`);process.exitCode=1;}
  if(currentInventory!==inventoryGenerated){console.error(`API inventory artifact is stale: ${inventoryPath}`);process.exitCode=1;}
  if(current===generated&&currentInventory===inventoryGenerated)console.log(`OpenAPI and API inventory artifacts are current (${httpOperations.length} operations)`);
}else{
  await Promise.all([writeFile(outputPath,generated,"utf8"),writeFile(inventoryPath,inventoryGenerated,"utf8")]);
  console.log(`Generated ${httpOperations.length} operations at ${outputPath} and ${inventoryPath}`);
}
