export type HttpOperation = {
  method: "get" | "post" | "patch" | "delete" | "put";
  path: string;
  operationId: string;
  tag: string;
  success: number | number[];
  public?: boolean;
  requestSchema?: string;
  requestMediaType?: string;
  responseSchema?: string;
  responseMediaType?: string;
};

export const httpOperations: HttpOperation[] = [
  { method:"get",path:"/api/v1/integration-providers",operationId:"listIntegrationProviders",tag:"Integrations",success:200,responseSchema:"IntegrationProviderDescriptorList" },
  { method:"get",path:"/api/v1/oauth/{providerId}/callback",operationId:"providerOAuthCallback",tag:"Integrations",success:302,public:true },
  { method:"get",path:"/api/v1/oauth/microsoft/callback",operationId:"microsoftOAuthCallback",tag:"Integrations",success:303,public:true },
  { method:"post",path:"/api/v1/integrations/microsoft/notifications",operationId:"microsoftChangeNotifications",tag:"Integrations",success:[200,202],public:true },
  { method:"post",path:"/api/v1/integrations/google/notifications",operationId:"googleCalendarChangeNotification",tag:"Integrations",success:204,public:true },
  { method:"get",path:"/api/v1/vaults/{vaultId}/people",operationId:"listPeople",tag:"People",success:200,responseSchema:"PersonSummaryList" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/people/{personId}",operationId:"getPersonContext",tag:"People",success:200,responseSchema:"PersonContext" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/people/{personId}/availability-proposals",operationId:"proposeSocialTime",tag:"People",success:202,requestSchema:"ProposeSocialTime",responseSchema:"JobHandle" },
  { method: "get", path: "/health/live", operationId: "healthLive", tag: "Health", success: 200, public: true, responseSchema: "Health" },
  { method: "get", path: "/health/ready", operationId: "healthReady", tag: "Health", success: 200, public: true, responseSchema: "Health" },
  { method: "get", path: "/api/v1/meta", operationId: "getMeta", tag: "Installation", success: 200, public: true, responseSchema: "Meta" },
  { method: "get", path: "/api/v1/preferences", operationId: "getPreferences", tag: "Installation", success: 200, responseSchema: "Preferences" },
  { method: "patch", path: "/api/v1/preferences", operationId: "updatePreferences", tag: "Installation", success: 200, requestSchema: "UpdatePreferences", responseSchema: "Preferences" },
  { method: "get", path: "/api/v1/status", operationId: "getStatus", tag: "Installation", success: 200, responseSchema: "SystemStatus" },
  { method: "get", path: "/api/v1/system-jobs", operationId: "listSystemJobs", tag: "Installation jobs", success: 200, responseSchema: "SystemJobList" },
  { method: "get", path: "/api/v1/system-jobs/{jobId}", operationId: "getSystemJob", tag: "Installation jobs", success: 200, responseSchema: "SystemJob" },
  { method: "post", path: "/api/v1/system-jobs/{jobId}/cancel", operationId: "cancelSystemJob", tag: "Installation jobs", success: 200, responseSchema: "SystemJob" },
  { method: "post", path: "/api/v1/system-jobs/{jobId}/retry", operationId: "retrySystemJob", tag: "Installation jobs", success: 202, responseSchema: "SystemJobHandle" },
  { method: "get", path: "/api/v1/system-jobs/{jobId}/events", operationId: "streamSystemJobEvents", tag: "Installation jobs", success: 200, responseSchema: "JobEvent", responseMediaType: "text/event-stream" },
  { method:"get",path:"/api/v1/backups",operationId:"listBackups",tag:"Backup and restore",success:200,responseSchema:"BackupList" },
  { method:"post",path:"/api/v1/backups",operationId:"createBackup",tag:"Backup and restore",success:202,requestSchema:"CreateBackup",responseSchema:"SystemJobHandle" },
  { method:"get",path:"/api/v1/backups/{backupId}",operationId:"getBackupManifest",tag:"Backup and restore",success:200,responseSchema:"BackupManifest" },
  { method:"get",path:"/api/v1/backups/{backupId}/download",operationId:"downloadBackup",tag:"Backup and restore",success:200,responseMediaType:"application/octet-stream" },
  { method:"post",path:"/api/v1/backups/{backupId}/verify",operationId:"verifyBackup",tag:"Backup and restore",success:202,responseSchema:"SystemJobHandle" },
  { method:"post",path:"/api/v1/restore-plans",operationId:"createRestorePlan",tag:"Backup and restore",success:202,requestSchema:"CreateRestorePlan",responseSchema:"SystemJobHandle" },
  { method:"post",path:"/api/v1/restore-plans/{restorePlanId}/apply",operationId:"applyRestore",tag:"Backup and restore",success:202,requestSchema:"ApplyRestore",responseSchema:"SystemJobHandle" },
  { method:"get",path:"/api/v1/host/resources",operationId:"getHostResources",tag:"Deployment",success:200,responseSchema:"HostResourceReport" },
  { method:"get",path:"/api/v1/deployment",operationId:"getDeploymentProfile",tag:"Deployment",success:200,responseSchema:"DeploymentProfile" },
  { method:"post",path:"/api/v1/deployment/checks",operationId:"checkDeployment",tag:"Deployment",success:202,requestSchema:"CheckDeployment",responseSchema:"SystemJobHandle" },
  { method:"post",path:"/api/v1/deployment/access-preview",operationId:"previewRemoteAccessSetup",tag:"Deployment",success:202,requestSchema:"PreviewRemoteAccessSetup",responseSchema:"SystemJobHandle" },
  { method:"get",path:"/api/v1/resource-policy",operationId:"getHostResourcePolicy",tag:"Deployment",success:200,responseSchema:"ResourcePolicy" },
  { method:"put",path:"/api/v1/resource-policy",operationId:"setHostResourcePolicy",tag:"Deployment",success:200,requestSchema:"SetHostResourcePolicy",responseSchema:"ResourcePolicy" },
  { method: "get", path: "/api/v1/vaults", operationId: "listVaults", tag: "Vaults", success: 200, responseSchema: "VaultList" },
  { method: "post", path: "/api/v1/vaults", operationId: "createVault", tag: "Vaults", success: 201, requestSchema: "CreateVault", responseSchema: "Vault" },
  { method: "get", path: "/api/v1/vaults/{vaultId}", operationId: "getVault", tag: "Vaults", success: 200, responseSchema: "Vault" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}", operationId: "updateVault", tag: "Vaults", success: 200, requestSchema: "UpdateVault", responseSchema: "Vault" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/purge", operationId: "purgeVault", tag: "Vaults", success: 202, requestSchema: "PurgeRequest", responseSchema: "SystemJobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/uploads", operationId: "createUpload", tag: "Files", success: 201, requestSchema: "CreateUpload", responseSchema: "UploadSession" },
  { method: "put", path: "/api/v1/vaults/{vaultId}/uploads/{uploadId}/parts/{partNumber}", operationId: "putUploadPart", tag: "Files", success: 204, requestMediaType: "application/octet-stream" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/uploads/{uploadId}/complete", operationId: "completeUpload", tag: "Files", success: 201, requestSchema: "CompleteUpload", responseSchema: "BlobSummary" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/uploads/{uploadId}", operationId: "cancelUpload", tag: "Files", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/blobs/{blobId}", operationId: "getBlobMetadata", tag: "Files", success: 200, responseSchema: "BlobSummary" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/blobs/{blobId}/content", operationId: "getBlobContent", tag: "Files", success: [200, 206], responseMediaType: "application/octet-stream" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/exports", operationId: "createExport", tag: "Exports", success: 202, requestSchema: "CreateExport", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/imports", operationId: "planImport", tag: "Imports", success: 202, requestSchema: "PlanImport", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/imports/{importId}", operationId: "getImport", tag: "Imports", success: 200, responseSchema: "ImportManifest" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/imports/{importId}/apply", operationId: "applyImport", tag: "Imports", success: 202, requestSchema: "ApplyImport", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/exports/{exportId}", operationId: "getExport", tag: "Exports", success: 200, responseSchema: "ExportManifest" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/exports/{exportId}/download", operationId: "downloadExport", tag: "Exports", success: 200, responseMediaType: "application/octet-stream" },
  { method: "post", path: "/api/v1/auth/bootstrap/options", operationId: "bootstrapOptions", tag: "Authentication", success: 200, public: true, requestSchema: "BootstrapOptionsInput", responseSchema: "WebAuthnOptions" },
  { method: "post", path: "/api/v1/auth/bootstrap/verify", operationId: "bootstrapVerify", tag: "Authentication", success: 201, public: true, requestSchema: "WebAuthnVerifyInput", responseSchema: "BootstrapResult" },
  { method: "post", path: "/api/v1/auth/login/options", operationId: "loginOptions", tag: "Authentication", success: 200, public: true, responseSchema: "WebAuthnOptions" },
  { method: "post", path: "/api/v1/auth/login/verify", operationId: "loginVerify", tag: "Authentication", success: 200, public: true, requestSchema: "WebAuthnVerifyInput", responseSchema: "Session" },
  { method: "get", path: "/api/v1/auth/session", operationId: "getSession", tag: "Authentication", success: 200, responseSchema: "Session" },
  { method: "post", path: "/api/v1/auth/logout", operationId: "logout", tag: "Authentication", success: 204 },
  { method: "post", path: "/api/v1/auth/recovery", operationId: "recoverAccount", tag: "Authentication", success: 200, public: true, requestSchema: "RecoveryRequest", responseSchema: "RecoverySession" },
  { method: "get", path: "/api/v1/auth/passkeys", operationId: "listPasskeys", tag: "Authentication", success: 200, responseSchema: "PasskeyList" },
  { method: "post", path: "/api/v1/auth/passkeys/options", operationId: "passkeyOptions", tag: "Authentication", success: 200, requestSchema: "PasskeyOptionsRequest", responseSchema: "WebAuthnOptions" },
  { method: "post", path: "/api/v1/auth/passkeys/verify", operationId: "passkeyVerify", tag: "Authentication", success: 201, requestSchema: "WebAuthnVerifyInput", responseSchema: "PasskeySummary" },
  { method: "delete", path: "/api/v1/auth/passkeys/{passkeyId}", operationId: "deletePasskey", tag: "Authentication", success: 204 },
  { method: "post", path: "/api/v1/auth/recovery-codes/rotate", operationId: "rotateRecoveryCodes", tag: "Authentication", success: 200, responseSchema: "RecoveryCodes" },
  { method: "get", path: "/api/v1/auth/sessions", operationId: "listSessions", tag: "Authentication", success: 200, responseSchema: "SessionSummaryList" },
  { method: "delete", path: "/api/v1/auth/sessions/{sessionId}", operationId: "revokeSession", tag: "Authentication", success: 204 },
  { method: "post", path: "/api/v1/auth/token/refresh", operationId: "refreshNativeToken", tag: "Authentication", success: 200, public: true, requestSchema: "RefreshNativeToken", responseSchema: "TokenPair" },
  { method: "post", path: "/api/v1/device-pairings", operationId: "createPairing", tag: "Devices", success: 201, public: true, requestSchema: "CreateDevicePairing", responseSchema: "DevicePairingChallenge" },
  { method: "post", path: "/api/v1/device-pairings/{pairingId}/approve", operationId: "approvePairing", tag: "Devices", success: 200, requestSchema: "ApproveDevicePairing", responseSchema: "DevicePairingApproval" },
  { method: "post", path: "/api/v1/device-pairings/{pairingId}/exchange", operationId: "exchangePairing", tag: "Devices", success: [200, 202], public: true, requestSchema: "ExchangeDevicePairing", responseSchema: "PairingExchangeResult" },
  { method: "get", path: "/api/v1/devices", operationId: "listDevices", tag: "Devices", success: 200, responseSchema: "DeviceList" },
  { method: "delete", path: "/api/v1/devices/{deviceId}", operationId: "revokeDevice", tag: "Devices", success: 204 },
  { method: "get", path: "/api/v1/devices/{deviceId}/cache-policy", operationId: "getDeviceCachePolicy", tag: "Devices", success: 200, responseSchema: "DeviceCachePolicy" },
  { method: "put", path: "/api/v1/devices/{deviceId}/cache-policy", operationId: "setDeviceCachePolicy", tag: "Devices", success: 200, requestSchema: "SetDeviceCachePolicy", responseSchema: "DeviceCachePolicy" },
  { method: "post", path: "/api/v1/devices/{deviceId}/cache-purge", operationId: "requestDeviceCachePurge", tag: "Devices", success: 202, requestSchema: "RequestDeviceCachePurge", responseSchema: "CachePurgeRequest" },
  { method: "get", path: "/api/v1/tokens", operationId: "listApiTokens", tag: "Devices", success: 200, responseSchema: "ApiTokenList" },
  { method: "post", path: "/api/v1/tokens", operationId: "createApiToken", tag: "Devices", success: 201, requestSchema: "CreateApiToken", responseSchema: "ApiTokenCreated" },
  { method: "delete", path: "/api/v1/tokens/{tokenId}", operationId: "revokeApiToken", tag: "Devices", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/notes", operationId: "listNotes", tag: "Notes", success: 200, responseSchema: "NoteList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/notes", operationId: "createNote", tag: "Notes", success: 201, requestSchema: "CreateNote", responseSchema: "Note" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/notes/{noteId}", operationId: "getNote", tag: "Notes", success: 200, responseSchema: "Note" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/notes/{noteId}", operationId: "updateNoteMetadata", tag: "Notes", success: 200, requestSchema: "UpdateNoteMetadata", responseSchema: "Note" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/notes/{noteId}", operationId: "trashNote", tag: "Notes", success: 204, requestSchema: "ExpectedNoteRevision" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/purge", operationId: "purgeNote", tag: "Notes", success: 202, requestSchema: "PurgeRequest", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/restore", operationId: "restoreTrashedNote", tag: "Notes", success: 200, requestSchema: "ExpectedNoteRevision", responseSchema: "Note" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/document", operationId: "getNoteDocument", tag: "Notes", success: 200, responseSchema: "DocumentRepresentation" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/edits", operationId: "editNote", tag: "Notes", success: 201, requestSchema: "EditNote", responseSchema: "NoteRevision" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/reprocess", operationId: "reprocessNote", tag: "Notes", success: 202, requestSchema: "ReprocessNote", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/revisions", operationId: "listNoteRevisions", tag: "Notes", success: 200, responseSchema: "NoteRevisionList" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/revisions/{revisionId}", operationId: "getNoteRevision", tag: "Notes", success: 200, responseSchema: "NoteRevision" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/revisions/{revisionId}/restore", operationId: "restoreNoteRevision", tag: "Notes", success: 201, requestSchema: "RestoreNoteRevision", responseSchema: "NoteRevision" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/corrections", operationId: "correctOrganization", tag: "Notes", success: 201, requestSchema: "CorrectNoteClassification", responseSchema: "CorrectionReceipt" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/labels", operationId: "listLabels", tag: "Organization", success: 200, responseSchema: "LabelList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/labels", operationId: "createLabel", tag: "Organization", success: 201, requestSchema: "CreateLabel", responseSchema: "Label" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/labels/{labelId}", operationId: "updateLabel", tag: "Organization", success: 200, requestSchema: "UpdateLabel", responseSchema: "Label" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/labels/{labelId}", operationId: "deleteLabel", tag: "Organization", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/labels", operationId: "getNoteLabels", tag: "Organization", success: 200, responseSchema: "NoteOrganization" },
  { method: "put", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/labels", operationId: "setNoteLabels", tag: "Organization", success: 200, requestSchema: "SetNoteLabels", responseSchema: "NoteOrganization" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/collections", operationId: "listCollections", tag: "Organization", success: 200, responseSchema: "CollectionList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/collections", operationId: "createCollection", tag: "Organization", success: 201, requestSchema: "CreateCollection", responseSchema: "Collection" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/collections/{collectionId}", operationId: "updateCollection", tag: "Organization", success: 200, requestSchema: "UpdateCollection", responseSchema: "Collection" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/collections/{collectionId}", operationId: "deleteCollection", tag: "Organization", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/collections/{collectionId}/items", operationId: "getCollectionItems", tag: "Organization", success: 200, responseSchema: "CollectionItems" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/rules", operationId: "listRoutingRules", tag: "Organization", success: 200, responseSchema: "RoutingRuleList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/rules", operationId: "createRoutingRule", tag: "Organization", success: 201, requestSchema: "CreateRoutingRule", responseSchema: "RoutingRule" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/rules/{ruleId}", operationId: "updateRoutingRule", tag: "Organization", success: 200, requestSchema: "UpdateRoutingRule", responseSchema: "RoutingRule" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/rules/{ruleId}", operationId: "deleteRoutingRule", tag: "Organization", success: 204 },
  { method: "post", path: "/api/v1/vaults/{vaultId}/rules/preview", operationId: "previewRoutingRule", tag: "Organization", success: 200, requestSchema: "RoutingRulePreview", responseSchema: "RulePreviewResult" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/relationships", operationId: "listRelationships", tag: "Organization", success: 200, responseSchema: "RelationshipList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/relationships", operationId: "createRelationship", tag: "Organization", success: 201, requestSchema: "CreateRelationship", responseSchema: "Relationship" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/relationships/{relationshipId}", operationId: "deleteRelationship", tag: "Organization", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/notes/{noteId}/related", operationId: "getRelatedNotes", tag: "Organization", success: 200, responseSchema: "RelatedResult" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/resurfacing/feedback", operationId: "resurfacingFeedback", tag: "Organization", success: 201, requestSchema: "ResurfacingFeedbackInput", responseSchema: "ResurfacingFeedback" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/captures", operationId: "createCapture", tag: "Capture", success: 201, requestSchema: "CreateCapture", responseSchema: "Note" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/url-captures", operationId: "createUrlCapture", tag: "Capture", success: 202, requestSchema: "CreateUrlCapture", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/generations", operationId: "generateArtifact", tag: "AI", success: 202, requestSchema: "GenerateArtifact", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/captures/{captureId}", operationId: "getCapture", tag: "Capture", success: 200, responseSchema: "Capture" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/connections",operationId:"listConnections",tag:"Integrations",success:200,responseSchema:"IntegrationConnectionList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/connections",operationId:"createConnection",tag:"Integrations",success:201,requestSchema:"CreateIntegrationConnection",responseSchema:"IntegrationConnection" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}",operationId:"getConnection",tag:"Integrations",success:200,responseSchema:"IntegrationConnection" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/authorize",operationId:"beginProviderAuthorization",tag:"Integrations",success:200,requestSchema:"AuthorizationRequest",responseSchema:"AuthorizationStart" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/reauthorize",operationId:"reauthorizeProvider",tag:"Integrations",success:200,requestSchema:"ReauthorizationRequest",responseSchema:"AuthorizationStart" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/capabilities",operationId:"getConnectionCapabilities",tag:"Integrations",success:200,responseSchema:"IntegrationCapabilityList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/probe",operationId:"probeConnection",tag:"Integrations",success:202,responseSchema:"JobHandle" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/mapping",operationId:"getConnectionMapping",tag:"Integrations",success:200,responseSchema:"ConnectionMapping" },
  { method:"put",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/mapping",operationId:"setConnectionMapping",tag:"Integrations",success:200,requestSchema:"SetConnectionMapping",responseSchema:"ConnectionMapping" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/resources",operationId:"listConnectionResources",tag:"Integrations",success:200,responseSchema:"ConnectorResourceList" },
  { method:"put",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/selection",operationId:"selectConnectionResources",tag:"Integrations",success:200,requestSchema:"ResourceSelectionInput",responseSchema:"ResourceSelection" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/sync",operationId:"syncConnection",tag:"Integrations",success:202,responseSchema:"JobHandle" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/sync-status",operationId:"getConnectionSyncStatus",tag:"Integrations",success:200,responseSchema:"ConnectorSyncStatus" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/schedule",operationId:"setConnectionSchedule",tag:"Integrations",success:200,requestSchema:"ConnectorSchedule",responseSchema:"ConnectorSchedule" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/disconnect-preview",operationId:"previewConnectionDisconnect",tag:"Integrations",success:200,requestSchema:"PreviewConnectionDisconnect",responseSchema:"ConnectionDisconnectPreview" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/source-objects",operationId:"listSourceObjects",tag:"Integrations",success:200,responseSchema:"SourceObjectList" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/source-objects/{sourceId}",operationId:"getSourceObject",tag:"Integrations",success:200,responseSchema:"SourceObjectDetail" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/source-objects/{sourceId}/refresh",operationId:"refreshSourceObject",tag:"Integrations",success:202,requestSchema:"RefreshSourceObject",responseSchema:"JobHandle" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/source-objects/{sourceId}/exclusion",operationId:"excludeSourceObject",tag:"Integrations",success:200,requestSchema:"SourceExclusionInput",responseSchema:"SourceExclusion" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/transcripts",operationId:"listTranscripts",tag:"Transcripts",success:200,responseSchema:"TranscriptList" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/transcripts/{transcriptId}",operationId:"getTranscript",tag:"Transcripts",success:200,responseSchema:"Transcript" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/transcripts/{transcriptId}",operationId:"correctTranscript",tag:"Transcripts",success:200,requestSchema:"CorrectTranscript",responseSchema:"Transcript" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/transcripts/{transcriptId}/lesson-association",operationId:"associateTranscriptWithLesson",tag:"Transcripts",success:201,requestSchema:"AssociateTranscript",responseSchema:"TranscriptAssociation" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/transcripts/{transcriptId}/analysis",operationId:"analyzeTranscript",tag:"Transcripts",success:202,requestSchema:"AnalyzeTranscript",responseSchema:"JobHandle" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/connections/{connectionId}/disconnect",operationId:"disconnectConnection",tag:"Integrations",success:200,requestSchema:"DisconnectIntegration",responseSchema:"IntegrationConnection" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/insights",operationId:"listInsights",tag:"Insights",success:200,responseSchema:"InsightList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/insights",operationId:"generateInsight",tag:"Insights",success:202,requestSchema:"GenerateInsight",responseSchema:"JobHandle" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/insights/{insightId}",operationId:"getInsight",tag:"Insights",success:200,responseSchema:"Insight" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/insights/{insightId}",operationId:"updateInsightFeedback",tag:"Insights",success:200,requestSchema:"UpdateInsight",responseSchema:"Insight" },
  { method:"delete",path:"/api/v1/vaults/{vaultId}/insights/{insightId}",operationId:"archiveInsight",tag:"Insights",success:204 },
  { method:"get",path:"/api/v1/vaults/{vaultId}/personal-data/items",operationId:"listPersonalDataItems",tag:"Personal Data",success:200,responseSchema:"PersonalDataItemList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/personal-data/sync",operationId:"syncSelectedPersonalData",tag:"Personal Data",success:202,requestSchema:"SyncSelectedPersonalData",responseSchema:"JobHandle" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/personal-data/policies",operationId:"getPersonalDataPolicies",tag:"Personal Data",success:200,responseSchema:"PersonalDataPolicies" },
  { method:"put",path:"/api/v1/vaults/{vaultId}/personal-data/policies",operationId:"setPersonalDataPolicies",tag:"Personal Data",success:200,requestSchema:"SetPersonalDataPolicies",responseSchema:"PersonalDataPolicies" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/personal-data/items/{itemId}",operationId:"getPersonalDataItem",tag:"Personal Data",success:200,responseSchema:"PersonalDataItem" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/personal-data/import-preview",operationId:"previewPersonalDataImport",tag:"Personal Data",success:201,requestSchema:"PreviewPersonalDataImport",responseSchema:"PersonalDataImportPreview" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/personal-data/import-previews/{previewId}",operationId:"getPersonalDataImportPreview",tag:"Personal Data",success:200,responseSchema:"PersonalDataImportPreview" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/personal-data/import-previews/{previewId}/apply",operationId:"applyPersonalDataImport",tag:"Personal Data",success:200,requestSchema:"ApplyPersonalDataImport",responseSchema:"PersonalDataImportReceipt" },
  { method:"delete",path:"/api/v1/vaults/{vaultId}/personal-data/items/{itemId}",operationId:"deletePersonalDataItem",tag:"Personal Data",success:204 },
  { method:"get",path:"/api/v1/vaults/{vaultId}/interests",operationId:"listInterests",tag:"Profile",success:200,responseSchema:"InterestList" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/interests/{interestId}",operationId:"getInterest",tag:"Profile",success:200,responseSchema:"Interest" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/interests/{interestId}",operationId:"updateInterest",tag:"Profile",success:200,requestSchema:"UpdateInterest",responseSchema:"Interest" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/personal-profile/refresh",operationId:"refreshPersonalProfile",tag:"Profile",success:202,requestSchema:"RefreshPersonalProfile",responseSchema:"JobHandle" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/personal-profile/rebuild",operationId:"rebuildPersonalProfile",tag:"Profile",success:202,requestSchema:"RebuildPersonalProfile",responseSchema:"JobHandle" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/personal-profile/interests",operationId:"listInterestClaims",tag:"Profile",success:200,responseSchema:"InterestList" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/personal-profile/interests/{interestId}/evidence",operationId:"getInterestEvidence",tag:"Profile",success:200,responseSchema:"InterestEvidenceList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/personal-profile/interests/{interestId}/decision",operationId:"decideInterestClaim",tag:"Profile",success:200,requestSchema:"DecideInterestClaim",responseSchema:"Interest" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/tasks", operationId: "listTasks", tag: "Tasks", success: 200, responseSchema: "TaskList" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/projects",operationId:"listProjects",tag:"Projects",success:200,responseSchema:"ProjectList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/projects",operationId:"createProject",tag:"Projects",success:201,requestSchema:"CreateProject",responseSchema:"Project" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/projects/{projectId}",operationId:"getProject",tag:"Projects",success:200,responseSchema:"Project" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/projects/{projectId}",operationId:"updateProject",tag:"Projects",success:200,requestSchema:"UpdateProject",responseSchema:"Project" },
  { method:"delete",path:"/api/v1/vaults/{vaultId}/projects/{projectId}",operationId:"archiveProject",tag:"Projects",success:200,responseSchema:"Project" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/ideas",operationId:"listIdeas",tag:"Projects",success:200,responseSchema:"IdeaList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/ideas",operationId:"createIdea",tag:"Projects",success:201,requestSchema:"CreateIdea",responseSchema:"Idea" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/ideas/{ideaId}",operationId:"getIdea",tag:"Projects",success:200,responseSchema:"Idea" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/ideas/{ideaId}",operationId:"updateIdea",tag:"Projects",success:200,requestSchema:"UpdateIdea",responseSchema:"Idea" },
  { method:"delete",path:"/api/v1/vaults/{vaultId}/ideas/{ideaId}",operationId:"archiveIdea",tag:"Projects",success:200,responseSchema:"Idea" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/goals",operationId:"listGoals",tag:"Projects",success:200,responseSchema:"GoalList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/goals",operationId:"createGoal",tag:"Projects",success:201,requestSchema:"CreateGoal",responseSchema:"Goal" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/goals/{goalId}",operationId:"getGoal",tag:"Projects",success:200,responseSchema:"Goal" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/goals/{goalId}",operationId:"updateGoal",tag:"Projects",success:200,requestSchema:"UpdateGoal",responseSchema:"Goal" },
  { method:"delete",path:"/api/v1/vaults/{vaultId}/goals/{goalId}",operationId:"archiveGoal",tag:"Projects",success:200,responseSchema:"Goal" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/memories",operationId:"listMemories",tag:"Profile",success:200,responseSchema:"MemoryList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/memories",operationId:"createMemory",tag:"Profile",success:201,requestSchema:"CreateMemory",responseSchema:"Memory" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/memories/{memoryId}",operationId:"getMemory",tag:"Profile",success:200,responseSchema:"Memory" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/memories/{memoryId}",operationId:"updateMemory",tag:"Profile",success:200,requestSchema:"UpdateMemory",responseSchema:"Memory" },
  { method:"delete",path:"/api/v1/vaults/{vaultId}/memories/{memoryId}",operationId:"archiveMemory",tag:"Profile",success:200,responseSchema:"Memory" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/personal-profile",operationId:"getPersonalProfile",tag:"Profile",success:200,responseSchema:"PersonalProfile" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/tasks", operationId: "createTask", tag: "Tasks", success: 201, requestSchema: "CreateTask", responseSchema: "Task" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/tasks/{taskId}", operationId: "getTask", tag: "Tasks", success: 200, responseSchema: "Task" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/tasks/{taskId}", operationId: "updateTask", tag: "Tasks", success: 200, requestSchema: "UpdateTask", responseSchema: "Task" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/tasks/{taskId}", operationId: "deleteTask", tag: "Tasks", success: 204, requestSchema: "ExpectedTaskRevision" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/tasks/{taskId}/execution-history", operationId: "getTaskExecutionHistory", tag: "Tasks", success: 200, responseSchema: "TaskExecutionHistory" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/reminders",operationId:"listReminders",tag:"Reminders",success:200,responseSchema:"ReminderList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/reminders",operationId:"createReminder",tag:"Reminders",success:201,requestSchema:"CreateReminder",responseSchema:"Reminder" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/reminders/{reminderId}",operationId:"updateReminder",tag:"Reminders",success:200,requestSchema:"UpdateReminder",responseSchema:"Reminder" },
  { method:"delete",path:"/api/v1/vaults/{vaultId}/reminders/{reminderId}",operationId:"deleteReminder",tag:"Reminders",success:204,requestSchema:"ExpectedNoteRevision" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/notifications",operationId:"listNotifications",tag:"Notifications",success:200,responseSchema:"NotificationList" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/notifications/{notificationId}",operationId:"updateNotification",tag:"Notifications",success:200,requestSchema:"UpdateNotification",responseSchema:"Notification" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-entities", operationId: "listCalendarEntities", tag: "Identity", success: 200, responseSchema: "CalendarEntityList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-entities", operationId: "createCalendarEntity", tag: "Identity", success: 201, requestSchema: "CreateCalendarEntity", responseSchema: "CalendarEntity" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-entities/{entityId}", operationId: "getCalendarEntity", tag: "Identity", success: 200, responseSchema: "CalendarEntity" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/calendar-entities/{entityId}", operationId: "updateCalendarEntity", tag: "Identity", success: 200, requestSchema: "UpdateCalendarEntity", responseSchema: "CalendarEntity" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/calendar-entities/{entityId}", operationId: "archiveCalendarEntity", tag: "Identity", success: 204 },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-entities/{entityId}/aliases", operationId: "addEntityAlias", tag: "Identity", success: 201, requestSchema: "AddEntityAlias", responseSchema: "EntityAlias" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/calendar-entities/{entityId}/aliases/{aliasId}", operationId: "removeEntityAlias", tag: "Identity", success: 204 },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-entities/merge-preview", operationId: "previewEntityMerge", tag: "Identity", success: 200, requestSchema: "PreviewEntityMerge", responseSchema: "Proposal" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-policies", operationId: "getCalendarPolicies", tag: "Calendar automation", success: 200, responseSchema: "CalendarPolicySet" },
  { method: "put", path: "/api/v1/vaults/{vaultId}/calendar-policies", operationId: "setCalendarPolicies", tag: "Calendar automation", success: 200, requestSchema: "CalendarPolicySetInput", responseSchema: "CalendarPolicySet" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-policies/dry-run", operationId: "dryRunCalendarPolicy", tag: "Calendar automation", success: 202, requestSchema: "PolicyDryRunInput", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-decisions", operationId: "listCalendarDecisions", tag: "Calendar automation", success: 200, responseSchema: "AutomationDecisionList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-decisions/{decisionId}/undo", operationId: "undoCalendarDecision", tag: "Calendar automation", success: 200, requestSchema: "UndoCalendarDecision", responseSchema: "CalendarDecisionUndoResult" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/commitments", operationId: "listCommitments", tag: "Commitments", success: 200, responseSchema: "CommitmentList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/commitments", operationId: "createCommitment", tag: "Commitments", success: 201, requestSchema: "CreateCommitment", responseSchema: "Commitment" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/commitments/{commitmentId}", operationId: "getCommitment", tag: "Commitments", success: 200, responseSchema: "CommitmentDetail" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/commitments/{commitmentId}", operationId: "updateCommitment", tag: "Commitments", success: 200, requestSchema: "UpdateCommitment", responseSchema: "Commitment" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/commitments/{commitmentId}", operationId: "archiveCommitment", tag: "Commitments", success: 204 },
  { method: "post", path: "/api/v1/vaults/{vaultId}/commitments/{commitmentId}/match", operationId: "rematchCommitment", tag: "Commitments", success: 202, requestSchema: "RematchCommitment", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendars", operationId: "listCalendars", tag: "Calendar", success: 200, responseSchema: "CalendarList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendars", operationId: "createCalendar", tag: "Calendar", success: 201, requestSchema: "CreateCalendar", responseSchema: "Calendar" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendars/{calendarId}", operationId: "getCalendar", tag: "Calendar", success: 200, responseSchema: "Calendar" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/calendars/{calendarId}", operationId: "updateCalendar", tag: "Calendar", success: 200, requestSchema: "UpdateCalendar", responseSchema: "Calendar" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/calendars/{calendarId}", operationId: "archiveCalendar", tag: "Calendar", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-events", operationId: "listCalendarEvents", tag: "Calendar", success: 200, responseSchema: "CalendarEventList" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-view", operationId: "getCalendarView", tag: "Calendar", success: 200, responseSchema: "CalendarView" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar/brief", operationId: "getCalendarBrief", tag: "Calendar", success: 200, responseSchema: "CalendarBrief" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar/brief-refresh", operationId: "refreshCalendarBrief", tag: "Calendar", success: 202, requestSchema: "CalendarBriefQuery", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-events", operationId: "createCalendarEvent", tag: "Calendar", success: 201, requestSchema: "CreateCalendarEvent", responseSchema: "CalendarEvent" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}", operationId: "getCalendarEvent", tag: "Calendar", success: 200, responseSchema: "CalendarEvent" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}", operationId: "updateCalendarEvent", tag: "Calendar", success: 200, requestSchema: "UpdateCalendarEvent", responseSchema: "CalendarEvent" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}", operationId: "trashCalendarEvent", tag: "Calendar", success: 204 },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/restore", operationId: "restoreCalendarEvent", tag: "Calendar", success: 200, responseSchema: "CalendarEvent" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/revisions", operationId: "listCalendarEventRevisions", tag: "Calendar", success: 200, responseSchema: "CalendarEventRevisionList" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/occurrences", operationId: "listEventOccurrences", tag: "Calendar", success: 200, responseSchema: "EventOccurrenceList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/exceptions", operationId: "createEventException", tag: "Calendar", success: 201, requestSchema: "OccurrenceExceptionInput", responseSchema: "OccurrenceException" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/exceptions/{exceptionId}", operationId: "updateEventException", tag: "Calendar", success: 200, requestSchema: "UpdateOccurrenceException", responseSchema: "OccurrenceException" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/exceptions/{exceptionId}", operationId: "removeEventException", tag: "Calendar", success: 204 },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar/free-busy", operationId: "calendarFreeBusy", tag: "Calendar", success: 200, requestSchema: "FreeBusyQuery", responseSchema: "FreeBusyResult" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar/conflicts", operationId: "listCalendarConflicts", tag: "Calendar", success: 200, responseSchema: "CalendarConflictList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar/preparation-plan", operationId: "previewPreparationPlan", tag: "Calendar", success: 202, requestSchema: "PreparationPlanInput", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-export", operationId: "exportCalendar", tag: "Calendar", success: 202, requestSchema: "CalendarExportInput", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-import-preview", operationId: "previewCalendarImport", tag: "Calendar", success: 202, requestSchema: "CalendarImportInput", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/private-context", operationId: "getPrivateEventContext", tag: "Calendar", success: 200, responseSchema: "PrivateEventContext" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/context-refresh", operationId: "refreshPrivateEventContext", tag: "Calendar", success: 202, requestSchema: "RefreshPrivateEventContext", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/reminder-plan", operationId: "setEventReminderPlan", tag: "Calendar", success: 200, requestSchema: "SetEventReminderPlan", responseSchema: "EventReminderPlan" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/reminder-plan", operationId: "getEventReminderPlan", tag: "Calendar", success: 200, responseSchema: "EventReminderPlan" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/prep-items", operationId: "createPrepItem", tag: "Calendar", success: 201, requestSchema: "CreatePrepItem", responseSchema: "PrepItem" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/prep-items/{prepId}", operationId: "updatePrepItem", tag: "Calendar", success: 200, requestSchema: "UpdatePrepItem", responseSchema: "PrepItem" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/calendar-events/{eventId}/prep-items/{prepId}", operationId: "removePrepItem", tag: "Calendar", success: 204 },
  { method:"post",path:"/api/v1/vaults/{vaultId}/calendar-events/{eventId}/provider-action-preview",operationId:"previewProviderCalendarAction",tag:"Calendar",success:200,requestSchema:"PreviewProviderCalendarAction",responseSchema:"Proposal" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/calendar-provider-actions",operationId:"listProviderCalendarActions",tag:"Calendar",success:200,responseSchema:"ProviderCalendarActionList" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/calendar-provider-actions/{actionId}",operationId:"getProviderCalendarAction",tag:"Calendar",success:200,responseSchema:"ProviderCalendarAction" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/calendar-provider-actions/{actionId}/reconcile",operationId:"reconcileProviderCalendarAction",tag:"Calendar",success:202,responseSchema:"JobHandle" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/calendar-provider-actions/{actionId}/cancel",operationId:"cancelPendingProviderCalendarAction",tag:"Calendar",success:200,responseSchema:"ProviderCalendarAction" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/search", operationId: "searchNotes", tag: "Search", success: [200, 202], requestSchema: "SearchRequest", responseSchema: "SearchResponse" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/chats", operationId: "listChats", tag: "Chats", success: 200, responseSchema: "ChatList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/chats", operationId: "createChat", tag: "Chats", success: 201, requestSchema: "CreateChat", responseSchema: "Chat" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/chats/{chatId}", operationId: "getChat", tag: "Chats", success: 200, responseSchema: "Chat" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/chats/{chatId}", operationId: "deleteChat", tag: "Chats", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/chats/{chatId}/messages", operationId: "listMessages", tag: "Chats", success: 200, responseSchema: "ChatMessageList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/chats/{chatId}/messages", operationId: "askNotes", tag: "Chats", success: 202, requestSchema: "CreateChatMessage", responseSchema: "AskHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/search/suggestions", operationId: "suggestSearch", tag: "Search", success: 200, responseSchema: "SearchSuggestions" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/citations/{citationId}", operationId: "resolveCitation", tag: "Search", success: 200, responseSchema: "ResolvedCitation" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/jobs", operationId: "listJobs", tag: "Jobs", success: 200, responseSchema: "JobList" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/jobs/{jobId}", operationId: "getJob", tag: "Jobs", success: 200, responseSchema: "Job" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/jobs/{jobId}/cancel", operationId: "cancelJob", tag: "Jobs", success: 200, responseSchema: "Job" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/jobs/{jobId}/retry", operationId: "retryJob", tag: "Jobs", success: 202, responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/jobs/{jobId}/events", operationId: "streamJobEvents", tag: "Jobs", success: 200, responseSchema: "JobEvent", responseMediaType: "text/event-stream" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/ai/status", operationId: "getAiStatus", tag: "AI", success: 200, responseSchema: "AiStatus" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/ai/policy", operationId: "getVaultAiPolicy", tag: "AI", success: 200, responseSchema: "VaultAiPolicy" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/ai/disclosure-preview", operationId: "previewAiDisclosure", tag: "AI", success: 200, requestSchema: "AiDisclosurePreviewInput", responseSchema: "AiDisclosurePreview" },
  { method: "put", path: "/api/v1/vaults/{vaultId}/ai/policy", operationId: "setVaultAiPolicy", tag: "AI", success: 200, requestSchema: "SetVaultAiPolicy", responseSchema: "VaultAiPolicy" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/agent-tools", operationId: "listAgentTools", tag: "Agent tools", success: 200, responseSchema: "ToolDescriptorList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/tool-runs", operationId: "runDomainTool", tag: "Agent tools", success: 202, requestSchema: "RunDomainTool", responseSchema: "JobHandle" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/tool-policies",operationId:"getToolPolicies",tag:"Agent tools",success:200,responseSchema:"ToolPolicySet" },
  { method:"put",path:"/api/v1/vaults/{vaultId}/tool-policies",operationId:"setToolPolicies",tag:"Agent tools",success:200,requestSchema:"SetToolPolicies",responseSchema:"ToolPolicySet" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/commands",operationId:"executeNaturalLanguageCommand",tag:"Agent tools",success:202,requestSchema:"ExecuteNaturalLanguageCommand",responseSchema:"JobHandle" },
  { method: "get", path: "/api/v1/ai/models", operationId: "listModelProfiles", tag: "AI", success: 200, responseSchema: "ModelProfileList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/ai/tests", operationId: "testAiSetup", tag: "AI", success: 202, requestSchema: "AiTestRequest", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/ai-operations", operationId: "listAiOperations", tag: "AI", success: 200, responseSchema: "AiOperationList" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/ai-operations/{operationId}", operationId: "getAiOperation", tag: "AI", success: 200, responseSchema: "AiOperation" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/ai-operations/{operationId}/undo", operationId: "undoAiOperation", tag: "AI", success: 200, requestSchema: "UndoAiOperation", responseSchema: "UndoReceipt" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/activity", operationId: "getActivity", tag: "AI", success: 200, responseSchema: "ActivityEventList" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/subjects", operationId: "listSubjects", tag: "School", success: 200, responseSchema: "SchoolSubjectList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/school/subjects", operationId: "createSubject", tag: "School", success: 201, requestSchema: "CreateSchoolSubject", responseSchema: "SchoolSubject" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/subjects/{subjectId}", operationId: "getSubject", tag: "School", success: 200, responseSchema: "SchoolSubject" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/school/subjects/{subjectId}", operationId: "updateSubject", tag: "School", success: 200, requestSchema: "UpdateSchoolSubject", responseSchema: "SchoolSubject" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/school/subjects/{subjectId}", operationId: "archiveSubject", tag: "School", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/courses", operationId: "listCourses", tag: "School", success: 200, responseSchema: "SchoolCourseList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/school/courses", operationId: "createCourse", tag: "School", success: 201, requestSchema: "CreateSchoolCourse", responseSchema: "SchoolCourse" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/courses/{courseId}", operationId: "getCourse", tag: "School", success: 200, responseSchema: "SchoolCourse" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/school/courses/{courseId}", operationId: "updateCourse", tag: "School", success: 200, requestSchema: "UpdateSchoolCourse", responseSchema: "SchoolCourse" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/school/courses/{courseId}", operationId: "archiveCourse", tag: "School", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/courses/{courseId}/materials", operationId: "listCourseMaterials", tag: "School", success: 200, responseSchema: "CourseMaterialLinkList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/school/courses/{courseId}/materials", operationId: "linkCourseMaterial", tag: "School", success: 201, requestSchema: "LinkCourseMaterial", responseSchema: "CourseMaterialLink" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/school/courses/{courseId}/materials/{materialLinkId}", operationId: "unlinkCourseMaterial", tag: "School", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/teachers", operationId: "listSchoolTeachers", tag: "School", success: 200, responseSchema: "TeacherViewList" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/overview", operationId: "getSchoolOverview", tag: "School", success: 200, responseSchema: "SchoolOverview" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/school/import-preview", operationId: "previewSchoolImport", tag: "School", success: 202, requestSchema: "PreviewSchoolImport", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/connections/{connectionId}/readiness", operationId: "getSchoolConnectionReadiness", tag: "School", success: 200, responseSchema: "SchoolReadinessReport" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/assignments", operationId: "listSchoolAssignments", tag: "School", success: 200, responseSchema: "SchoolAssignmentList" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/assignments/{assignmentId}", operationId: "getSchoolAssignment", tag: "School", success: 200, responseSchema: "SchoolAssignment" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/school/assignments", operationId: "createManualSchoolAssignment", tag: "School", success: 201, requestSchema: "CreateSchoolAssignment", responseSchema: "SchoolAssignment" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/school/assignments/{assignmentId}", operationId: "updateSchoolAssignmentOverlay", tag: "School", success: 200, requestSchema: "UpdateSchoolAssignment", responseSchema: "SchoolAssignment" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/school/assignments/{assignmentId}", operationId: "archiveSchoolAssignment", tag: "School", success: 204 },
  { method: "post", path: "/api/v1/vaults/{vaultId}/school/assignments/{assignmentId}/archive", operationId: "archiveSchoolAssignmentOverlay", tag: "School", success: 200, requestSchema: "ArchiveSchoolAssignmentOverlay", responseSchema: "SchoolAssignment" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/lessons", operationId: "listSchoolLessons", tag: "School", success: 200, responseSchema: "SchoolLessonList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/school/lessons", operationId: "createSchoolLesson", tag: "School", success: 201, requestSchema: "CreateSchoolLesson", responseSchema: "SchoolLesson" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/lessons/{schoolLessonId}", operationId: "getSchoolLesson", tag: "School", success: 200, responseSchema: "SchoolLesson" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/school/lessons/{schoolLessonId}", operationId: "updateSchoolLesson", tag: "School", success: 200, requestSchema: "UpdateSchoolLesson", responseSchema: "SchoolLesson" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/school/lessons/{schoolLessonId}", operationId: "archiveSchoolLesson", tag: "School", success: 204 },
  { method: "post", path: "/api/v1/vaults/{vaultId}/school/catch-up-plans", operationId: "createCatchUpPlan", tag: "School", success: 202, requestSchema: "CreateCatchUpPlan", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/assessments", operationId: "listAssessments", tag: "School", success: 200, responseSchema: "SchoolAssessmentList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/school/assessments", operationId: "createAssessment", tag: "School", success: 201, requestSchema: "CreateSchoolAssessment", responseSchema: "SchoolAssessment" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/school/assessments/{assessmentId}", operationId: "getAssessment", tag: "School", success: 200, responseSchema: "SchoolAssessment" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/school/assessments/{assessmentId}", operationId: "updateAssessment", tag: "School", success: 200, requestSchema: "UpdateSchoolAssessment", responseSchema: "SchoolAssessment" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/school/assessments/{assessmentId}", operationId: "archiveAssessment", tag: "School", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/attendance/records", operationId: "listAttendanceRecords", tag: "Attendance", success: 200, responseSchema: "AttendanceRecordList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/attendance/records", operationId: "createAttendanceRecord", tag: "Attendance", success: 201, requestSchema: "CreateAttendanceRecord", responseSchema: "AttendanceRecord" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/attendance/records/{attendanceRecordId}", operationId: "getAttendanceRecord", tag: "Attendance", success: 200, responseSchema: "AttendanceRecord" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/attendance/records/{attendanceRecordId}", operationId: "updateAttendanceRecord", tag: "Attendance", success: 200, requestSchema: "UpdateAttendanceRecord", responseSchema: "AttendanceRecord" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/attendance/records/{attendanceRecordId}", operationId: "archiveAttendanceRecord", tag: "Attendance", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/attendance/summary", operationId: "getAttendanceSummary", tag: "Attendance", success: 200, responseSchema: "AttendanceSummary" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/attendance/catch-up-preview", operationId: "previewAttendanceCatchUp", tag: "Attendance", success: 202, requestSchema: "PreviewAttendanceCatchUp", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/performance/grades", operationId: "listGrades", tag: "Performance", success: 200, responseSchema: "PerformanceGradeList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/performance/grades", operationId: "createGrade", tag: "Performance", success: 201, requestSchema: "CreatePerformanceGrade", responseSchema: "PerformanceGrade" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/performance/grades/{gradeId}", operationId: "getGrade", tag: "Performance", success: 200, responseSchema: "PerformanceGrade" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/performance/grades/{gradeId}", operationId: "updateGrade", tag: "Performance", success: 200, requestSchema: "UpdatePerformanceGrade", responseSchema: "PerformanceGrade" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/performance/grades/{gradeId}", operationId: "archiveGrade", tag: "Performance", success: 204 },
  { method:"get",path:"/api/v1/vaults/{vaultId}/school/grades",operationId:"listGradeRecords",tag:"School grades",success:200,responseSchema:"GradeRecordList" },
  { method:"post",path:"/api/v1/vaults/{vaultId}/school/grades",operationId:"createGradeRecord",tag:"School grades",success:201,requestSchema:"CreateGradeRecord",responseSchema:"GradeRecord" },
  { method:"get",path:"/api/v1/vaults/{vaultId}/school/grades/{gradeRecordId}",operationId:"getGradeRecord",tag:"School grades",success:200,responseSchema:"GradeRecord" },
  { method:"patch",path:"/api/v1/vaults/{vaultId}/school/grades/{gradeRecordId}",operationId:"updateGradeRecord",tag:"School grades",success:200,requestSchema:"UpdateGradeRecord",responseSchema:"GradeRecord" },
  { method:"delete",path:"/api/v1/vaults/{vaultId}/school/grades/{gradeRecordId}",operationId:"archiveGradeRecord",tag:"School grades",success:200,requestSchema:"ArchiveGradeRecord",responseSchema:"GradeRecord" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/performance/targets", operationId: "listPerformanceTargets", tag: "Performance", success: 200, responseSchema: "PerformanceTargetList" },
  { method: "put", path: "/api/v1/vaults/{vaultId}/performance/targets/{courseId}", operationId: "setPerformanceTarget", tag: "Performance", success: 200, requestSchema: "SetPerformanceTarget", responseSchema: "PerformanceTarget" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/performance/targets/{courseId}", operationId: "removePerformanceTarget", tag: "Performance", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/performance/summary", operationId: "getPerformanceSummary", tag: "Performance", success: 200, responseSchema: "PerformanceSummary" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/performance/recommendations", operationId: "generateStudyRecommendations", tag: "Performance", success: 202, requestSchema: "GeneratePerformanceRecommendations", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/plans", operationId: "listStudyPlans", tag: "Study", success: 200, responseSchema: "StudyPlanList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/plans", operationId: "createStudyPlan", tag: "Study", success: 202, requestSchema: "CreateStudyPlan", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/plans/{studyPlanId}", operationId: "getStudyPlan", tag: "Study", success: 200, responseSchema: "StudyPlan" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/study/plans/{studyPlanId}", operationId: "updateStudyPlan", tag: "Study", success: 200, requestSchema: "UpdateStudyPlan", responseSchema: "StudyPlan" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/plans/{studyPlanId}/withdraw", operationId: "withdrawStudyPlan", tag: "Study", success: 201, requestSchema: "WithdrawStudyPlan", responseSchema: "StudyWithdrawalProposal" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/study/plans/{studyPlanId}", operationId: "archiveStudyPlan", tag: "Study", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/exercises", operationId: "listStudyExercises", tag: "Study", success: 200, responseSchema: "StudyExerciseList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/exercises", operationId: "generateStudyExercise", tag: "Study", success: 202, requestSchema: "CreateStudyExercise", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/exercises/{exerciseId}", operationId: "getStudyExercise", tag: "Study", success: 200, responseSchema: "StudyExercise" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/exercises/{exerciseId}/attempts", operationId: "submitStudyAttempt", tag: "Study", success: 201, requestSchema: "CreateStudyAttempt", responseSchema: "StudyAttempt" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/attempts", operationId: "listStudyAttempts", tag: "Study", success: 200, responseSchema: "StudyAttemptList" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/attempts/{attemptId}", operationId: "getStudyAttempt", tag: "Study", success: 200, responseSchema: "StudyAttempt" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/attempts/{attemptId}/feedback", operationId: "gradeStudyAttempt", tag: "Study", success: 202, requestSchema: "RequestStudyFeedback", responseSchema: "JobHandle" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/study/attempts/{attemptId}/feedback", operationId: "correctStudyFeedback", tag: "Study", success: 200, requestSchema: "CorrectStudyFeedback", responseSchema: "StudyAttempt" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/activities", operationId: "createStudyActivity", tag: "Study", success: 202, requestSchema: "CreateStudyActivity", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/activities", operationId: "listStudyActivities", tag: "Study", success: 200, responseSchema: "StudyActivityList" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/activities/{activityId}", operationId: "getStudyActivity", tag: "Study", success: 200, responseSchema: "StudyActivity" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/activities/{activityId}/responses", operationId: "submitStudyResponse", tag: "Study", success: 202, requestSchema: "SubmitStudyResponse", responseSchema: "JobHandle" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/study/activities/{activityId}", operationId: "archiveStudyActivity", tag: "Study", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/sessions", operationId: "listStudySessions", tag: "Study", success: 200, responseSchema: "StudySessionList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/sessions", operationId: "createStudySession", tag: "Study", success: 201, requestSchema: "CreateStudySession", responseSchema: "StudySession" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/sessions/{studySessionId}", operationId: "getStudySession", tag: "Study", success: 200, responseSchema: "StudySession" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/sessions/{studySessionId}/actions", operationId: "applyStudySessionAction", tag: "Study", success: 200, requestSchema: "StudySessionAction", responseSchema: "StudySession" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/study/sessions/{studySessionId}", operationId: "archiveStudySession", tag: "Study", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/knowledge-gaps", operationId: "listKnowledgeGaps", tag: "Study", success: 200, responseSchema: "KnowledgeGapList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/knowledge-gaps", operationId: "createReportedKnowledgeGap", tag: "Study", success: 201, requestSchema: "CreateReportedKnowledgeGap", responseSchema: "KnowledgeGap" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/study/knowledge-gaps/{gapId}", operationId: "updateKnowledgeGap", tag: "Study", success: 200, requestSchema: "UpdateKnowledgeGap", responseSchema: "KnowledgeGap" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/performance/knowledge-gaps/{gapId}", operationId: "correctKnowledgeGap", tag: "Performance", success: 200, requestSchema: "CorrectKnowledgeGap", responseSchema: "KnowledgeGap" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/decks", operationId: "listFlashcardDecks", tag: "Study", success: 200, responseSchema: "FlashcardDeckList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/decks", operationId: "createFlashcardDeck", tag: "Study", success: 201, requestSchema: "CreateFlashcardDeck", responseSchema: "FlashcardDeck" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/decks/{flashcardDeckId}", operationId: "getFlashcardDeck", tag: "Study", success: 200, responseSchema: "FlashcardDeck" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/study/decks/{flashcardDeckId}", operationId: "updateFlashcardDeck", tag: "Study", success: 200, requestSchema: "UpdateFlashcardDeck", responseSchema: "FlashcardDeck" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/study/decks/{flashcardDeckId}", operationId: "archiveFlashcardDeck", tag: "Study", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/cards", operationId: "listFlashcards", tag: "Study", success: 200, responseSchema: "FlashcardList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/cards", operationId: "createFlashcard", tag: "Study", success: 201, requestSchema: "CreateFlashcard", responseSchema: "Flashcard" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/cards/{flashcardId}", operationId: "getFlashcard", tag: "Study", success: 200, responseSchema: "Flashcard" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/study/cards/{flashcardId}", operationId: "updateFlashcard", tag: "Study", success: 200, requestSchema: "UpdateFlashcard", responseSchema: "Flashcard" },
  { method: "delete", path: "/api/v1/vaults/{vaultId}/study/cards/{flashcardId}", operationId: "archiveFlashcard", tag: "Study", success: 204 },
  { method: "get", path: "/api/v1/vaults/{vaultId}/study/review-queue", operationId: "getFlashcardReviewQueue", tag: "Study", success: 200, responseSchema: "FlashcardReviewQueue" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/cards/{flashcardId}/reviews", operationId: "recordFlashcardReview", tag: "Study", success: 201, requestSchema: "RecordFlashcardReview", responseSchema: "FlashcardReview" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/study/flashcards/{flashcardId}/reviews", operationId: "reviewFlashcard", tag: "Study", success: 201, requestSchema: "ReviewFlashcard", responseSchema: "FlashcardReviewReceipt" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/scheduler/preferences", operationId: "getSchedulerPreferences", tag: "Scheduler", success: 200, responseSchema: "SchedulerPreferences" },
  { method: "put", path: "/api/v1/vaults/{vaultId}/scheduler/preferences", operationId: "setSchedulerPreferences", tag: "Scheduler", success: 200, requestSchema: "SetSchedulerPreferences", responseSchema: "SchedulerPreferences" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/scheduler/preview", operationId: "previewSchedule", tag: "Scheduler", success: 202, requestSchema: "SchedulePreviewRequest", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/scheduler/constraints", operationId: "getSchedulingConstraints", tag: "Scheduler", success: 200, responseSchema: "SchedulingConstraints" },
  { method: "put", path: "/api/v1/vaults/{vaultId}/scheduler/constraints", operationId: "setSchedulingConstraints", tag: "Scheduler", success: 200, requestSchema: "SetSchedulingConstraints", responseSchema: "SchedulingConstraints" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/scheduler/plans", operationId: "proposeSchedule", tag: "Scheduler", success: 202, requestSchema: "ProposeSchedule", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/scheduler/replan", operationId: "previewReplan", tag: "Scheduler", success: 202, requestSchema: "ScheduleReplanRequest", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/scheduler/replans", operationId: "proposeReplan", tag: "Scheduler", success: 202, requestSchema: "ScheduleReplanRequest", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/scheduler/explanations/{proposalId}", operationId: "getScheduleExplanation", tag: "Scheduler", success: 200, responseSchema: "ScheduleExplanation" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/proposals", operationId: "listProposals", tag: "Proposals", success: 200, responseSchema: "ProposalList" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/proposals", operationId: "createProposal", tag: "Proposals", success: 201, requestSchema: "ProposalInput", responseSchema: "Proposal" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/proposals/{proposalId}", operationId: "getProposal", tag: "Proposals", success: 200, responseSchema: "Proposal" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/proposals/{proposalId}/reject", operationId: "rejectProposal", tag: "Proposals", success: 200, requestSchema: "RejectProposal", responseSchema: "Proposal" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/proposals/{proposalId}/accept", operationId: "acceptProposal", tag: "Proposals", success: 202, requestSchema: "AcceptProposal", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/proposals/{proposalId}/undo", operationId: "undoProposalApplication", tag: "Proposals", success: 200, requestSchema: "UndoProposal", responseSchema: "ProposalUndoReceipt" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/ideas/{ideaId}/promotion-preview", operationId: "previewIdeaPromotion", tag: "Profile", success: 201, requestSchema: "PreviewIdeaPromotion", responseSchema: "Proposal" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/ideas/{ideaId}/project-proposal", operationId: "proposeIdeaProject", tag: "Profile", success: 201, requestSchema: "ProposeIdeaProject", responseSchema: "Proposal" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/tasks/{taskId}/breakdown", operationId: "proposeTaskBreakdown", tag: "Tasks", success: 202, requestSchema: "ProposeTaskBreakdown", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/execution-sessions", operationId: "startExecutionSession", tag: "Execution", success: 201, requestSchema: "StartExecutionSession", responseSchema: "ExecutionSession" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/execution-sessions/{executionSessionId}", operationId: "getExecutionSession", tag: "Execution", success: 200, responseSchema: "ExecutionSession" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/execution-sessions/{executionSessionId}/transition", operationId: "transitionExecutionSession", tag: "Execution", success: 200, requestSchema: "TransitionExecutionSession", responseSchema: "ExecutionSession" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/index/status", operationId: "getIndexStatus", tag: "Search", success: 200, responseSchema: "IndexStatus" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/index/rebuild", operationId: "rebuildIndex", tag: "Search", success: 202, requestSchema: "RebuildIndexRequest", responseSchema: "JobHandle" },
  { method: "post", path: "/api/v1/worker/heartbeat", operationId: "workerHeartbeat", tag: "Workers", success: 200, requestSchema: "WorkerHeartbeatRequest", responseSchema: "WorkerHeartbeatResponse" },
  { method: "post", path: "/api/v1/worker/jobs/claim", operationId: "claimWorkerJob", tag: "Workers", success: [200, 204], requestSchema: "ClaimWorkerJobRequest", responseSchema: "WorkerLease" },
  { method: "get", path: "/api/v1/worker/jobs/{jobId}/input", operationId: "getWorkerJobInput", tag: "Workers", success: 200, responseSchema: "WorkerJobInput" },
  { method: "get", path: "/api/v1/worker/jobs/{jobId}/sources/{sourceId}", operationId: "getWorkerJobSource", tag: "Workers", success: 200, responseSchema: "WorkerSourceInput" },
  { method: "post", path: "/api/v1/worker/jobs/{jobId}/evidence", operationId: "getWorkerJobEvidence", tag: "Workers", success: 200, requestSchema: "WorkerEvidenceRequest", responseSchema: "WorkerEvidencePacket" },
  { method: "post", path: "/api/v1/worker/jobs/{jobId}/index-batches", operationId: "appendWorkerIndexBatch", tag: "Workers", success: 200, requestSchema: "WorkerIndexBatch", responseSchema: "IndexBatchAck" },
  { method: "post", path: "/api/v1/worker/jobs/{jobId}/heartbeat", operationId: "renewWorkerLease", tag: "Workers", success: 200, requestSchema: "WorkerLeaseHeartbeat", responseSchema: "LeaseState" },
  { method: "post", path: "/api/v1/worker/jobs/{jobId}/events", operationId: "appendWorkerEvents", tag: "Workers", success: 200, requestSchema: "WorkerProgressEvents", responseSchema: "EventAck" },
  { method: "post", path: "/api/v1/worker/jobs/{jobId}/complete", operationId: "completeWorkerJob", tag: "Workers", success: 200, requestSchema: "WorkerComplete", responseSchema: "Job" },
  { method: "post", path: "/api/v1/worker/jobs/{jobId}/fail", operationId: "failWorkerJob", tag: "Workers", success: 200, requestSchema: "WorkerFail", responseSchema: "Job" },
  { method: "get", path: "/api/v1/workers", operationId: "listWorkers", tag: "Workers", success: 200, responseSchema: "WorkerList" },
  { method: "patch", path: "/api/v1/workers/{workerId}", operationId: "configureWorker", tag: "Workers", success: 200, requestSchema: "ConfigureWorker", responseSchema: "WorkerSummary" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/today", operationId: "getToday", tag: "Today", success: 200, responseSchema: "Today" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/scheduler/recommendations", operationId: "getNextActionCandidates", tag: "Scheduler", success: 200, responseSchema: "NextActionSet" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/next-actions", operationId: "getNextActions", tag: "Scheduler", success: 200, responseSchema: "NextActionSet" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/momentum/summary", operationId: "getMomentumSummary", tag: "Study", success: 200, responseSchema: "MomentumSummary" },
  { method: "patch", path: "/api/v1/vaults/{vaultId}/momentum/preferences", operationId: "setMomentumPreferences", tag: "Study", success: 200, requestSchema: "UpdateMomentumPreferences", responseSchema: "MomentumPreferences" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/sync/pull", operationId: "pullSync", tag: "Sync", success: 200, responseSchema: "SyncBatch" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/sync/push", operationId: "pushSync", tag: "Sync", success: 200, requestSchema: "PushSync", responseSchema: "SyncAck" },
  { method: "post", path: "/api/v1/vaults/{vaultId}/sync/snapshots", operationId: "createSyncSnapshot", tag: "Sync", success: 202, requestSchema: "CreateSyncSnapshot", responseSchema: "JobHandle" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/sync/ws", operationId: "openSyncSocket", tag: "Sync", success: 101, responseSchema: "SyncSocketServerFrame" },
  { method: "get", path: "/api/v1/vaults/{vaultId}/events", operationId: "streamVaultEvents", tag: "Sync", success: 200, responseSchema: "VaultChangeEvent", responseMediaType: "text/event-stream" }
];
