import { instantFromWallClock, isSupportedTimezone } from "./recurrence.js";

export type CalendarImportItem={
  sourceUid:string;sequence:number;title:string;startsAt:string|null;endsAt:string|null;timezone:string;
  recurrence:{frequency:"weekly";interval:number;count:number}|null;
  sourceStatus:"active"|"cancelled";action:"create"|"create_series"|"cancel"|"blocked";
  reasonCodes:string[];ignoredInvitationFields:string[];
};

function unescapeText(value:string){return value.replace(/\\n/gi,"\n").replace(/\\,/g,",").replace(/\\;/g,";").replace(/\\\\/g,"\\");}
function unfold(value:string){return value.replace(/\r?\n[ \t]/g,"").split(/\r?\n/);}
function property(line:string){const colon=line.indexOf(":");if(colon<1)return null;const left=line.slice(0,colon),value=line.slice(colon+1),parts=left.split(";");return{name:parts[0].toUpperCase(),parameters:Object.fromEntries(parts.slice(1).map(item=>{const index=item.indexOf("=");return[index<0?item.toUpperCase():item.slice(0,index).toUpperCase(),index<0?"":item.slice(index+1)];})),value};}
function compactInstant(value:string,timezone:string,dateOnly=false){
  if(dateOnly||/^\d{8}$/.test(value)){const match=value.match(/^(\d{4})(\d{2})(\d{2})$/);if(!match)return null;const wall=new Date(`${match[1]}-${match[2]}-${match[3]}T00:00:00.000Z`);return instantFromWallClock(wall,timezone).toISOString();}
  const match=value.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})(Z?)$/);if(!match)return null;
  const iso=`${match[1]}-${match[2]}-${match[3]}T${match[4]}:${match[5]}:${match[6]}.000Z`;
  return match[7]==="Z"?new Date(iso).toISOString():instantFromWallClock(new Date(iso),timezone).toISOString();
}
function weeklyRule(value:string|undefined){if(!value)return{rule:null,reason:null};const values=Object.fromEntries(value.split(";").map(item=>{const index=item.indexOf("=");return[item.slice(0,index).toUpperCase(),item.slice(index+1)];}));if(values.FREQ!=="WEEKLY")return{rule:null,reason:"unsupported_recurrence_frequency"};const interval=values.INTERVAL?Number(values.INTERVAL):1,count=values.COUNT?Number(values.COUNT):52;if(!Number.isInteger(interval)||interval<1||interval>52||!Number.isInteger(count)||count<1||count>520||values.UNTIL||values.BYDAY||Object.keys(values).some(key=>!["FREQ","INTERVAL","COUNT"].includes(key)))return{rule:null,reason:"unsupported_recurrence_shape"};return{rule:{frequency:"weekly" as const,interval,count},reason:null};}

export function parseCalendarImport(source:string,defaultTimezone:string){
  if(!isSupportedTimezone(defaultTimezone))throw new Error("unsupported_timezone");if(Buffer.byteLength(source,"utf8")>10*1024*1024)throw new Error("calendar_import_too_large");
  const lines=unfold(source);if(lines.length>100_000||!lines.some(line=>line.trim().toUpperCase()==="BEGIN:VCALENDAR")||!lines.some(line=>line.trim().toUpperCase()==="END:VCALENDAR"))throw new Error("invalid_ics_calendar");
  const method=lines.map(property).find(item=>item?.name==="METHOD")?.value.toUpperCase()??null,items:CalendarImportItem[]=[];let block:Array<ReturnType<typeof property>>|null=null;
  for(const line of lines){const parsed=property(line);if(line.trim().toUpperCase()==="BEGIN:VEVENT"){if(block)throw new Error("nested_ics_event");block=[];continue;}if(line.trim().toUpperCase()==="END:VEVENT"){if(!block)throw new Error("unmatched_ics_event_end");const values=new Map<string,NonNullable<ReturnType<typeof property>>[]>();for(const item of block)if(item)values.set(item.name,[...(values.get(item.name)??[]),item]);const one=(name:string)=>values.get(name)?.[0];const uid=one("UID")?.value.trim(),summary=unescapeText(one("SUMMARY")?.value.trim()??"Untitled event").slice(0,500),start=one("DTSTART"),end=one("DTEND"),zone=start?.parameters.TZID??defaultTimezone;const reasonCodes:string[]=[];if(!uid||uid.length>500)reasonCodes.push("missing_or_invalid_uid");if(!isSupportedTimezone(zone))reasonCodes.push("unsupported_timezone");const startsAt=start&&isSupportedTimezone(zone)?compactInstant(start.value,zone,start.parameters.VALUE==="DATE"):null,endsAt=end&&isSupportedTimezone(zone)?compactInstant(end.value,end.parameters.TZID??zone,end.parameters.VALUE==="DATE"):null;if(!startsAt||!endsAt||Date.parse(endsAt)<=Date.parse(startsAt))reasonCodes.push("invalid_event_range");const recurrence=weeklyRule(one("RRULE")?.value);if(recurrence.reason)reasonCodes.push(recurrence.reason);const sourceStatus=one("STATUS")?.value.toUpperCase()==="CANCELLED"?"cancelled" as const:"active" as const,ignoredInvitationFields=[...values.keys()].filter(name=>["ATTENDEE","ORGANIZER","RSVP"].includes(name));if(method&&!["PUBLISH"].includes(method))reasonCodes.push("invitation_method_ignored");let action:CalendarImportItem["action"]=sourceStatus==="cancelled"?"cancel":recurrence.rule?"create_series":"create";if(reasonCodes.some(code=>code.startsWith("invalid_")||code.startsWith("missing_")||code.startsWith("unsupported_")))action="blocked";items.push({sourceUid:uid??`missing-${items.length+1}`,sequence:Number(one("SEQUENCE")?.value??0)||0,title:summary,startsAt,endsAt,timezone:zone,recurrence:recurrence.rule,sourceStatus,action,reasonCodes,ignoredInvitationFields});block=null;continue;}if(block)block.push(parsed);}
  if(block)throw new Error("unterminated_ics_event");if(items.length>10_000)throw new Error("calendar_import_too_many_events");return{method,items,warnings:[...(method&&method!=="PUBLISH"?[`Calendar method ${method} was treated as data only; no invitations or responses will be sent.`]:[]),...(items.some(item=>item.ignoredInvitationFields.length)?["Attendee, organizer, and RSVP fields were ignored."]:[])]};
}
