import { describe, expect, it } from "vitest";
import { buildSchedulePreview, explainScheduleReasons, selectNextActionCandidates, selectNextActionPlacement } from "./scheduler.js";

const preferences = { timezone:"Europe/Oslo", protectedWindows:[{days:[1,2,3,4,5],startLocal:"00:00",endLocal:"08:00",label:"sleep"}], preferredWindows:[], dailyLimitMinutes:120, breakMinutes:10, minBlockMinutes:25, maxBlockMinutes:60, allowSplit:true };
describe("deterministic scheduler",()=>{
  it("places known effort around busy time and reports unknown effort",()=>{const result=buildSchedulePreview({horizon:{startsAt:"2026-09-21T06:00:00.000Z",endsAt:"2026-09-21T14:00:00.000Z"},preferences,busy:[{startsAt:"2026-09-21T07:00:00.000Z",endsAt:"2026-09-21T08:00:00.000Z"}],tasks:[{id:"known",remainingMinutes:60,earliestStart:null,dueAt:null,priority:3,allowSplit:true,minBlockMinutes:null,maxBlockMinutes:null},{id:"unknown",remainingMinutes:null,earliestStart:null,dueAt:null,priority:5,allowSplit:true,minBlockMinutes:null,maxBlockMinutes:null}]});expect(result.placements).toHaveLength(1);expect(result.placements[0].startsAt).toBe("2026-09-21T06:00:00.000Z");expect(result.unscheduled).toEqual([{taskId:"unknown",remainingMinutes:null,reasonCodes:["unknown_effort"]}]);});
  it("does not exceed daily capacity",()=>{const result=buildSchedulePreview({horizon:{startsAt:"2026-09-21T06:00:00.000Z",endsAt:"2026-09-21T20:00:00.000Z"},preferences:{...preferences,dailyLimitMinutes:60},busy:[],tasks:[{id:"large",remainingMinutes:120,earliestStart:null,dueAt:null,priority:3,allowSplit:true,minBlockMinutes:null,maxBlockMinutes:null}]});expect(result.placements.reduce((sum,item)=>sum+item.minutes,0)).toBe(60);expect(result.unscheduled[0].remainingMinutes).toBe(60);});
  it("uses an accepted focus block before proposing another slot",()=>{const result=selectNextActionPlacement({horizon:{startsAt:"2026-09-21T07:00:00.000Z",endsAt:"2026-09-22T07:00:00.000Z"},preferences,busy:[],tasks:[{id:"task",remainingMinutes:null,earliestStart:null,dueAt:null,priority:0,allowSplit:true,minBlockMinutes:null,maxBlockMinutes:null}],scheduledFocus:[{taskId:"task",eventId:"event",startsAt:"2026-09-21T07:00:00.000Z",endsAt:"2026-09-21T07:30:00.000Z"}]});expect(result).toMatchObject({taskId:"task",source:"scheduled_focus_block",durationMinutes:30,canStartNow:true});});
  it("never invents a next-action duration for unknown work",()=>{const result=selectNextActionPlacement({horizon:{startsAt:"2026-09-21T07:00:00.000Z",endsAt:"2026-09-22T07:00:00.000Z"},preferences,busy:[],scheduledFocus:[],tasks:[{id:"unknown",remainingMinutes:null,earliestStart:null,dueAt:null,priority:5,allowSplit:true,minBlockMinutes:null,maxBlockMinutes:null}]});expect(result).toBeNull();});
  it("explains the first feasible deterministic action",()=>{const result=selectNextActionPlacement({horizon:{startsAt:"2026-09-21T07:00:00.000Z",endsAt:"2026-09-22T07:00:00.000Z"},preferences,busy:[{startsAt:"2026-09-21T07:00:00.000Z",endsAt:"2026-09-21T08:00:00.000Z"}],scheduledFocus:[],tasks:[{id:"due",remainingMinutes:25,earliestStart:null,dueAt:"2026-09-21T12:00:00.000Z",priority:2,allowSplit:true,minBlockMinutes:null,maxBlockMinutes:null}]});expect(result).toMatchObject({taskId:"due",source:"deterministic_slot",startsAt:"2026-09-21T08:00:00.000Z",durationMinutes:25});expect(result?.reasonCodes).toContain("earliest_feasible");expect(result?.explanation).toContain("recorded deadline");});
  it("returns a bounded candidate set without inventing effort",()=>{const result=selectNextActionCandidates({horizon:{startsAt:"2026-09-21T07:00:00.000Z",endsAt:"2026-09-22T07:00:00.000Z"},preferences,busy:[],availableMinutes:30,limit:3,scheduledFocus:[{taskId:"scheduled",eventId:"event",startsAt:"2026-09-21T07:00:00.000Z",endsAt:"2026-09-21T07:45:00.000Z"}],tasks:[{id:"scheduled",remainingMinutes:45,earliestStart:null,dueAt:null,priority:1,allowSplit:true,minBlockMinutes:null,maxBlockMinutes:null},{id:"known",remainingMinutes:60,earliestStart:null,dueAt:"2026-09-21T18:00:00.000Z",priority:3,allowSplit:true,minBlockMinutes:null,maxBlockMinutes:null},{id:"unknown",remainingMinutes:null,earliestStart:null,dueAt:null,priority:5,allowSplit:true,minBlockMinutes:null,maxBlockMinutes:null}]});expect(result).toHaveLength(3);expect(result[0]).toMatchObject({taskId:"scheduled",source:"scheduled_focus_block",durationMinutes:45,fitsAvailableMinutes:false});expect(result[1]).toMatchObject({taskId:"known",source:"deterministic_slot",durationMinutes:30,fitsAvailableMinutes:true});expect(result[2]).toMatchObject({taskId:"unknown",source:"unsized_task",durationMinutes:null,durationKnown:false,reasonCodes:["unknown_effort"]});});
  it("turns scheduler codes into bounded factual explanations",()=>{expect(explainScheduleReasons(["unknown_effort","no_capacity"])).toEqual(["Remaining effort is unknown, so no duration or slot was invented.","No remaining capacity satisfies the current calendar, protected-time, break, and daily-limit constraints."]);expect(explainScheduleReasons(["future_reason"])[0]).toBe("Recorded scheduler reason: future_reason.");});
});
