export type WeeklyReviewCounts={tasksCompleted:number;tasksOpen:number;studySessionsCompleted:number;observedStudySeconds:number;attendanceKnown:number;attendanceUnknown:number;absences:number;upcomingAssessments:number;activeProjects:number|null;openIdeas:number|null;plannedCalendarEvents:number|null;personalDataItems:number};
export function buildWeeklyReview(counts:WeeklyReviewCounts,scope:string[]){
  const requested=new Set(scope);const coverage=[] as Array<{domain:any;status:"observed"|"partial"|"unavailable"|"not_requested";recordCount:number;limitation:string|null}>;const add=(domain:string,count:number|null,limitation:string|null=null)=>coverage.push({domain,status:requested.has(domain)?limitation?"unavailable":"observed":"not_requested",recordCount:requested.has(domain)?count??0:0,limitation:requested.has(domain)?limitation:null});
  add("tasks",counts.tasksCompleted+counts.tasksOpen);add("study",counts.studySessionsCompleted);add("attendance",counts.attendanceKnown+counts.attendanceUnknown);add("assessments",counts.upcomingAssessments);add("projects",counts.activeProjects);add("ideas",counts.openIdeas);add("calendar",counts.plannedCalendarEvents);add("personal_data",counts.personalDataItems,counts.personalDataItems?null:"No personal-data observations were imported for this window.");
  const facts=[
    {key:"tasks_completed",label:"Tasks completed",value:counts.tasksCompleted,unit:"tasks",epistemicStatus:"observed" as const,evidenceIds:[]},{key:"observed_study_minutes",label:"Explicit active study time",value:Math.floor(counts.observedStudySeconds/60),unit:"minutes",epistemicStatus:"observed" as const,evidenceIds:[]},{key:"attendance_known",label:"Known attendance records",value:counts.attendanceKnown,unit:"records",epistemicStatus:"observed" as const,evidenceIds:[]},{key:"attendance_unknown",label:"Unknown attendance records",value:counts.attendanceUnknown,unit:"records",epistemicStatus:"unknown" as const,evidenceIds:[]},{key:"upcoming_assessments",label:"Upcoming assessments",value:counts.upcomingAssessments,unit:"assessments",epistemicStatus:"planned" as const,evidenceIds:[]},{key:"planned_calendar_events",label:"Planned calendar events",value:counts.plannedCalendarEvents,unit:"events",epistemicStatus:"planned" as const,evidenceIds:[]}
  ].filter(item=>requested.has(item.key.startsWith("tasks")?"tasks":item.key.startsWith("observed_study")?"study":item.key.startsWith("attendance")?"attendance":item.key.startsWith("upcoming")?"assessments":"calendar"));
  const suggestions=[] as Array<{text:string;evidenceIds:string[];bounded:true}>;if(requested.has("tasks")&&counts.tasksOpen)suggestions.push({text:`Review ${counts.tasksOpen} open task${counts.tasksOpen===1?"":"s"} and choose only feasible next actions.`,evidenceIds:[],bounded:true});if(requested.has("attendance")&&counts.absences)suggestions.push({text:"Check missed lessons for source-linked catch-up material; missing coverage must remain unknown.",evidenceIds:[],bounded:true});if(requested.has("assessments")&&counts.upcomingAssessments)suggestions.push({text:"Review upcoming assessment dates and material scope before scheduling study blocks.",evidenceIds:[],bounded:true});
  return {facts,coverage,suggestions};
}
